`timescale 1ns/1ps
// jev_mesh_2x2_tb.v -- self-checking testbench generated by the WASMApollo EDA; the expected
// values are the fabric's golden model (RefSim). Run: iverilog -o tb jev_mesh_2x2.v jev_mesh_2x2_tb.v && vvp tb

module jev_mesh_2x2_tb;
  reg clk = 1'b0;
  reg rst = 1'b1;
  reg n_valid = 0;
  reg [1:0] n_kind = 0;
  reg [31:0] n_d0 = 0;
  reg [31:0] n_d1 = 0;
  reg s_ready = 0;
  reg w_valid = 0;
  reg [31:0] w_p0 = 0;
  reg [31:0] w_p1 = 0;
  reg e_ready = 0;
  wire n_ready;
  wire s_valid;
  wire [1:0] s_kind;
  wire [31:0] s_d0;
  wire [31:0] s_d1;
  wire w_ready;
  wire e_valid;
  wire [31:0] e_p0;
  wire [31:0] e_p1;
  integer errors = 0;

  jev_mesh_2x2 dut (.clk(clk), .rst(rst), .n_valid(n_valid), .n_kind(n_kind), .n_d0(n_d0), .n_d1(n_d1), .s_ready(s_ready), .w_valid(w_valid), .w_p0(w_p0), .w_p1(w_p1), .e_ready(e_ready), .n_ready(n_ready), .s_valid(s_valid), .s_kind(s_kind), .s_d0(s_d0), .s_d1(s_d1), .w_ready(w_ready), .e_valid(e_valid), .e_p0(e_p0), .e_p1(e_p1));

  always #5 clk = ~clk;
  task tick;
    begin
      @(posedge clk);
      #1;
    end
  endtask

  initial begin
    // vector 0
    n_valid = 1'h1;
    n_kind = 2'h0;
    n_d0 = 32'h00007B06;
    n_d1 = 32'h000040FB;
    s_ready = 1'h1;
    w_valid = 1'h1;
    w_p0 = 32'h000090B6;
    w_p1 = 32'h0000CF5A;
    e_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h1) begin $display("FAIL vector 0: n_ready = %h, want %h", n_ready, 1'h1); errors = errors + 1; end
    if (s_valid !== 1'h1) begin $display("FAIL vector 0: s_valid = %h, want %h", s_valid, 1'h1); errors = errors + 1; end
    if (s_kind !== 2'h0) begin $display("FAIL vector 0: s_kind = %h, want %h", s_kind, 2'h0); errors = errors + 1; end
    if (s_d0 !== 32'h00007B06) begin $display("FAIL vector 0: s_d0 = %h, want %h", s_d0, 32'h00007B06); errors = errors + 1; end
    if (s_d1 !== 32'h000040FB) begin $display("FAIL vector 0: s_d1 = %h, want %h", s_d1, 32'h000040FB); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 0: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 0: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h000090B6) begin $display("FAIL vector 0: e_p0 = %h, want %h", e_p0, 32'h000090B6); errors = errors + 1; end
    if (e_p1 !== 32'h0000CF5A) begin $display("FAIL vector 0: e_p1 = %h, want %h", e_p1, 32'h0000CF5A); errors = errors + 1; end
    // vector 1
    n_valid = 1'h1;
    n_kind = 2'h0;
    n_d0 = 32'h000099B2;
    n_d1 = 32'h0000B1AB;
    s_ready = 1'h1;
    w_valid = 1'h1;
    w_p0 = 32'h00002B5E;
    w_p1 = 32'h000098E9;
    e_ready = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h0) begin $display("FAIL vector 1: n_ready = %h, want %h", n_ready, 1'h0); errors = errors + 1; end
    if (s_valid !== 1'h0) begin $display("FAIL vector 1: s_valid = %h, want %h", s_valid, 1'h0); errors = errors + 1; end
    if (s_kind !== 2'h0) begin $display("FAIL vector 1: s_kind = %h, want %h", s_kind, 2'h0); errors = errors + 1; end
    if (s_d0 !== 32'h000099B2) begin $display("FAIL vector 1: s_d0 = %h, want %h", s_d0, 32'h000099B2); errors = errors + 1; end
    if (s_d1 !== 32'h0000B1AB) begin $display("FAIL vector 1: s_d1 = %h, want %h", s_d1, 32'h0000B1AB); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 1: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h1) begin $display("FAIL vector 1: e_valid = %h, want %h", e_valid, 1'h1); errors = errors + 1; end
    if (e_p0 !== 32'h00002B5E) begin $display("FAIL vector 1: e_p0 = %h, want %h", e_p0, 32'h00002B5E); errors = errors + 1; end
    if (e_p1 !== 32'h000098E9) begin $display("FAIL vector 1: e_p1 = %h, want %h", e_p1, 32'h000098E9); errors = errors + 1; end
    // vector 2
    n_valid = 1'h1;
    n_kind = 2'h0;
    n_d0 = 32'h0000B6EC;
    n_d1 = 32'h0000952A;
    s_ready = 1'h0;
    w_valid = 1'h1;
    w_p0 = 32'h0000E783;
    w_p1 = 32'h0000EACD;
    e_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h0) begin $display("FAIL vector 2: n_ready = %h, want %h", n_ready, 1'h0); errors = errors + 1; end
    if (s_valid !== 1'h1) begin $display("FAIL vector 2: s_valid = %h, want %h", s_valid, 1'h1); errors = errors + 1; end
    if (s_kind !== 2'h0) begin $display("FAIL vector 2: s_kind = %h, want %h", s_kind, 2'h0); errors = errors + 1; end
    if (s_d0 !== 32'h0000B6EC) begin $display("FAIL vector 2: s_d0 = %h, want %h", s_d0, 32'h0000B6EC); errors = errors + 1; end
    if (s_d1 !== 32'h0000952A) begin $display("FAIL vector 2: s_d1 = %h, want %h", s_d1, 32'h0000952A); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 2: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 2: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 2: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 2: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    // vector 3
    n_valid = 1'h0;
    n_kind = 2'h0;
    n_d0 = 32'h0000C21A;
    n_d1 = 32'h00003F53;
    s_ready = 1'h1;
    w_valid = 1'h1;
    w_p0 = 32'h000076B5;
    w_p1 = 32'h00003D19;
    e_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h1) begin $display("FAIL vector 3: n_ready = %h, want %h", n_ready, 1'h1); errors = errors + 1; end
    if (s_valid !== 1'h0) begin $display("FAIL vector 3: s_valid = %h, want %h", s_valid, 1'h0); errors = errors + 1; end
    if (s_kind !== 2'h0) begin $display("FAIL vector 3: s_kind = %h, want %h", s_kind, 2'h0); errors = errors + 1; end
    if (s_d0 !== 32'h00000000) begin $display("FAIL vector 3: s_d0 = %h, want %h", s_d0, 32'h00000000); errors = errors + 1; end
    if (s_d1 !== 32'h00000000) begin $display("FAIL vector 3: s_d1 = %h, want %h", s_d1, 32'h00000000); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 3: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 3: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 3: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 3: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    // vector 4
    n_valid = 1'h1;
    n_kind = 2'h1;
    n_d0 = 32'h00004C06;
    n_d1 = 32'h0000CA5F;
    s_ready = 1'h1;
    w_valid = 1'h0;
    w_p0 = 32'h00002CDB;
    w_p1 = 32'h000026CF;
    e_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h1) begin $display("FAIL vector 4: n_ready = %h, want %h", n_ready, 1'h1); errors = errors + 1; end
    if (s_valid !== 1'h1) begin $display("FAIL vector 4: s_valid = %h, want %h", s_valid, 1'h1); errors = errors + 1; end
    if (s_kind !== 2'h1) begin $display("FAIL vector 4: s_kind = %h, want %h", s_kind, 2'h1); errors = errors + 1; end
    if (s_d0 !== 32'h00004C06) begin $display("FAIL vector 4: s_d0 = %h, want %h", s_d0, 32'h00004C06); errors = errors + 1; end
    if (s_d1 !== 32'h0000CA5F) begin $display("FAIL vector 4: s_d1 = %h, want %h", s_d1, 32'h0000CA5F); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 4: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 4: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 4: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 4: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    // vector 5
    n_valid = 1'h1;
    n_kind = 2'h1;
    n_d0 = 32'h00009E9A;
    n_d1 = 32'h000064AC;
    s_ready = 1'h0;
    w_valid = 1'h1;
    w_p0 = 32'h00000207;
    w_p1 = 32'h00000065;
    e_ready = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h0) begin $display("FAIL vector 5: n_ready = %h, want %h", n_ready, 1'h0); errors = errors + 1; end
    if (s_valid !== 1'h1) begin $display("FAIL vector 5: s_valid = %h, want %h", s_valid, 1'h1); errors = errors + 1; end
    if (s_kind !== 2'h1) begin $display("FAIL vector 5: s_kind = %h, want %h", s_kind, 2'h1); errors = errors + 1; end
    if (s_d0 !== 32'h00009E9A) begin $display("FAIL vector 5: s_d0 = %h, want %h", s_d0, 32'h00009E9A); errors = errors + 1; end
    if (s_d1 !== 32'h000064AC) begin $display("FAIL vector 5: s_d1 = %h, want %h", s_d1, 32'h000064AC); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 5: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 5: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 5: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 5: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    // vector 6
    n_valid = 1'h1;
    n_kind = 2'h1;
    n_d0 = 32'h00009D21;
    n_d1 = 32'h0000681E;
    s_ready = 1'h1;
    w_valid = 1'h1;
    w_p0 = 32'h0000AC23;
    w_p1 = 32'h0000D117;
    e_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h1) begin $display("FAIL vector 6: n_ready = %h, want %h", n_ready, 1'h1); errors = errors + 1; end
    if (s_valid !== 1'h1) begin $display("FAIL vector 6: s_valid = %h, want %h", s_valid, 1'h1); errors = errors + 1; end
    if (s_kind !== 2'h1) begin $display("FAIL vector 6: s_kind = %h, want %h", s_kind, 2'h1); errors = errors + 1; end
    if (s_d0 !== 32'h00009D21) begin $display("FAIL vector 6: s_d0 = %h, want %h", s_d0, 32'h00009D21); errors = errors + 1; end
    if (s_d1 !== 32'h0000681E) begin $display("FAIL vector 6: s_d1 = %h, want %h", s_d1, 32'h0000681E); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 6: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 6: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 6: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 6: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    // vector 7
    n_valid = 1'h0;
    n_kind = 2'h1;
    n_d0 = 32'h0000A93E;
    n_d1 = 32'h0000C78D;
    s_ready = 1'h1;
    w_valid = 1'h1;
    w_p0 = 32'h0000048B;
    w_p1 = 32'h000087E0;
    e_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h1) begin $display("FAIL vector 7: n_ready = %h, want %h", n_ready, 1'h1); errors = errors + 1; end
    if (s_valid !== 1'h0) begin $display("FAIL vector 7: s_valid = %h, want %h", s_valid, 1'h0); errors = errors + 1; end
    if (s_kind !== 2'h0) begin $display("FAIL vector 7: s_kind = %h, want %h", s_kind, 2'h0); errors = errors + 1; end
    if (s_d0 !== 32'h00000000) begin $display("FAIL vector 7: s_d0 = %h, want %h", s_d0, 32'h00000000); errors = errors + 1; end
    if (s_d1 !== 32'h00000000) begin $display("FAIL vector 7: s_d1 = %h, want %h", s_d1, 32'h00000000); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 7: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 7: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 7: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 7: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    // vector 8
    n_valid = 1'h1;
    n_kind = 2'h2;
    n_d0 = 32'h00009829;
    n_d1 = 32'h000099A1;
    s_ready = 1'h0;
    w_valid = 1'h1;
    w_p0 = 32'h0000965E;
    w_p1 = 32'h00002496;
    e_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h0) begin $display("FAIL vector 8: n_ready = %h, want %h", n_ready, 1'h0); errors = errors + 1; end
    if (s_valid !== 1'h1) begin $display("FAIL vector 8: s_valid = %h, want %h", s_valid, 1'h1); errors = errors + 1; end
    if (s_kind !== 2'h2) begin $display("FAIL vector 8: s_kind = %h, want %h", s_kind, 2'h2); errors = errors + 1; end
    if (s_d0 !== 32'h00009829) begin $display("FAIL vector 8: s_d0 = %h, want %h", s_d0, 32'h00009829); errors = errors + 1; end
    if (s_d1 !== 32'h000099A1) begin $display("FAIL vector 8: s_d1 = %h, want %h", s_d1, 32'h000099A1); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 8: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 8: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 8: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 8: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    // vector 9
    n_valid = 1'h1;
    n_kind = 2'h2;
    n_d0 = 32'h0000EE70;
    n_d1 = 32'h0000E23E;
    s_ready = 1'h1;
    w_valid = 1'h0;
    w_p0 = 32'h00005F2F;
    w_p1 = 32'h00002A90;
    e_ready = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h1) begin $display("FAIL vector 9: n_ready = %h, want %h", n_ready, 1'h1); errors = errors + 1; end
    if (s_valid !== 1'h1) begin $display("FAIL vector 9: s_valid = %h, want %h", s_valid, 1'h1); errors = errors + 1; end
    if (s_kind !== 2'h2) begin $display("FAIL vector 9: s_kind = %h, want %h", s_kind, 2'h2); errors = errors + 1; end
    if (s_d0 !== 32'h0000EE70) begin $display("FAIL vector 9: s_d0 = %h, want %h", s_d0, 32'h0000EE70); errors = errors + 1; end
    if (s_d1 !== 32'h0000E23E) begin $display("FAIL vector 9: s_d1 = %h, want %h", s_d1, 32'h0000E23E); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 9: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 9: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 9: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 9: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    // vector 10
    n_valid = 1'h1;
    n_kind = 2'h2;
    n_d0 = 32'h00009BCF;
    n_d1 = 32'h0000BA3F;
    s_ready = 1'h1;
    w_valid = 1'h1;
    w_p0 = 32'h00009220;
    w_p1 = 32'h000052D9;
    e_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h1) begin $display("FAIL vector 10: n_ready = %h, want %h", n_ready, 1'h1); errors = errors + 1; end
    if (s_valid !== 1'h1) begin $display("FAIL vector 10: s_valid = %h, want %h", s_valid, 1'h1); errors = errors + 1; end
    if (s_kind !== 2'h2) begin $display("FAIL vector 10: s_kind = %h, want %h", s_kind, 2'h2); errors = errors + 1; end
    if (s_d0 !== 32'h00009BCF) begin $display("FAIL vector 10: s_d0 = %h, want %h", s_d0, 32'h00009BCF); errors = errors + 1; end
    if (s_d1 !== 32'h0000BA3F) begin $display("FAIL vector 10: s_d1 = %h, want %h", s_d1, 32'h0000BA3F); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 10: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 10: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 10: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 10: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    // vector 11
    n_valid = 1'h0;
    n_kind = 2'h2;
    n_d0 = 32'h00003789;
    n_d1 = 32'h0000AAF1;
    s_ready = 1'h0;
    w_valid = 1'h1;
    w_p0 = 32'h0000F617;
    w_p1 = 32'h0000E2FB;
    e_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h1) begin $display("FAIL vector 11: n_ready = %h, want %h", n_ready, 1'h1); errors = errors + 1; end
    if (s_valid !== 1'h0) begin $display("FAIL vector 11: s_valid = %h, want %h", s_valid, 1'h0); errors = errors + 1; end
    if (s_kind !== 2'h0) begin $display("FAIL vector 11: s_kind = %h, want %h", s_kind, 2'h0); errors = errors + 1; end
    if (s_d0 !== 32'h00000000) begin $display("FAIL vector 11: s_d0 = %h, want %h", s_d0, 32'h00000000); errors = errors + 1; end
    if (s_d1 !== 32'h00000000) begin $display("FAIL vector 11: s_d1 = %h, want %h", s_d1, 32'h00000000); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 11: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 11: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 11: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 11: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    // vector 12
    n_valid = 1'h1;
    n_kind = 2'h3;
    n_d0 = 32'h00009F0C;
    n_d1 = 32'h000045C6;
    s_ready = 1'h1;
    w_valid = 1'h1;
    w_p0 = 32'h00003DF3;
    w_p1 = 32'h000084B6;
    e_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h1) begin $display("FAIL vector 12: n_ready = %h, want %h", n_ready, 1'h1); errors = errors + 1; end
    if (s_valid !== 1'h1) begin $display("FAIL vector 12: s_valid = %h, want %h", s_valid, 1'h1); errors = errors + 1; end
    if (s_kind !== 2'h3) begin $display("FAIL vector 12: s_kind = %h, want %h", s_kind, 2'h3); errors = errors + 1; end
    if (s_d0 !== 32'h00009F0C) begin $display("FAIL vector 12: s_d0 = %h, want %h", s_d0, 32'h00009F0C); errors = errors + 1; end
    if (s_d1 !== 32'h000045C6) begin $display("FAIL vector 12: s_d1 = %h, want %h", s_d1, 32'h000045C6); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 12: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 12: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 12: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 12: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    // vector 13
    n_valid = 1'h1;
    n_kind = 2'h3;
    n_d0 = 32'h00000883;
    n_d1 = 32'h00003E27;
    s_ready = 1'h1;
    w_valid = 1'h1;
    w_p0 = 32'h0000D68F;
    w_p1 = 32'h0000EA1A;
    e_ready = 1'h0;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h1) begin $display("FAIL vector 13: n_ready = %h, want %h", n_ready, 1'h1); errors = errors + 1; end
    if (s_valid !== 1'h1) begin $display("FAIL vector 13: s_valid = %h, want %h", s_valid, 1'h1); errors = errors + 1; end
    if (s_kind !== 2'h3) begin $display("FAIL vector 13: s_kind = %h, want %h", s_kind, 2'h3); errors = errors + 1; end
    if (s_d0 !== 32'h00000883) begin $display("FAIL vector 13: s_d0 = %h, want %h", s_d0, 32'h00000883); errors = errors + 1; end
    if (s_d1 !== 32'h00003E27) begin $display("FAIL vector 13: s_d1 = %h, want %h", s_d1, 32'h00003E27); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 13: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 13: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 13: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 13: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    // vector 14
    n_valid = 1'h1;
    n_kind = 2'h3;
    n_d0 = 32'h0000712A;
    n_d1 = 32'h0000DE7F;
    s_ready = 1'h0;
    w_valid = 1'h0;
    w_p0 = 32'h0000A4BD;
    w_p1 = 32'h0000C75C;
    e_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h0) begin $display("FAIL vector 14: n_ready = %h, want %h", n_ready, 1'h0); errors = errors + 1; end
    if (s_valid !== 1'h1) begin $display("FAIL vector 14: s_valid = %h, want %h", s_valid, 1'h1); errors = errors + 1; end
    if (s_kind !== 2'h3) begin $display("FAIL vector 14: s_kind = %h, want %h", s_kind, 2'h3); errors = errors + 1; end
    if (s_d0 !== 32'h0000712A) begin $display("FAIL vector 14: s_d0 = %h, want %h", s_d0, 32'h0000712A); errors = errors + 1; end
    if (s_d1 !== 32'h0000DE7F) begin $display("FAIL vector 14: s_d1 = %h, want %h", s_d1, 32'h0000DE7F); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 14: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 14: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 14: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 14: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    // vector 15
    n_valid = 1'h0;
    n_kind = 2'h3;
    n_d0 = 32'h00003668;
    n_d1 = 32'h0000FA98;
    s_ready = 1'h1;
    w_valid = 1'h1;
    w_p0 = 32'h0000CD1F;
    w_p1 = 32'h000083F4;
    e_ready = 1'h1;
    rst = 1'b1;
    tick;
    rst = 1'b0;
    repeat (24) tick;
    if (n_ready !== 1'h1) begin $display("FAIL vector 15: n_ready = %h, want %h", n_ready, 1'h1); errors = errors + 1; end
    if (s_valid !== 1'h0) begin $display("FAIL vector 15: s_valid = %h, want %h", s_valid, 1'h0); errors = errors + 1; end
    if (s_kind !== 2'h0) begin $display("FAIL vector 15: s_kind = %h, want %h", s_kind, 2'h0); errors = errors + 1; end
    if (s_d0 !== 32'h00000000) begin $display("FAIL vector 15: s_d0 = %h, want %h", s_d0, 32'h00000000); errors = errors + 1; end
    if (s_d1 !== 32'h00000000) begin $display("FAIL vector 15: s_d1 = %h, want %h", s_d1, 32'h00000000); errors = errors + 1; end
    if (w_ready !== 1'h0) begin $display("FAIL vector 15: w_ready = %h, want %h", w_ready, 1'h0); errors = errors + 1; end
    if (e_valid !== 1'h0) begin $display("FAIL vector 15: e_valid = %h, want %h", e_valid, 1'h0); errors = errors + 1; end
    if (e_p0 !== 32'h00000000) begin $display("FAIL vector 15: e_p0 = %h, want %h", e_p0, 32'h00000000); errors = errors + 1; end
    if (e_p1 !== 32'h00000000) begin $display("FAIL vector 15: e_p1 = %h, want %h", e_p1, 32'h00000000); errors = errors + 1; end
    if (errors == 0) $display("PASS jev_mesh_2x2: 16 vectors");
    else $display("FAIL jev_mesh_2x2: %0d mismatches", errors);
    $finish;
  end
endmodule
