-- jev_mesh_2x2.vhd -- generated by the WASMApollo EDA (heapvm vgpu apollo) from typed fabric `jev_mesh_2x2`.
-- 297 LUT4 cells, 132 word PEs, 133 registers, 11 combinational levels.
-- Clocking matches the vFPGA / vASIC fabric: each rising clk edge latches every register
-- from the settled levels; rst (synchronous) loads the fabric's initial state.
-- Jev microcode ROM `jev_route`: controller state -> Jev's answer -> select code (LSB first: rom_21 rom_22)
--   state  answer        p      code
--   0      stage         1.000  00
--   1      load          1.000  01
--   2      reset         1.000  11
--   3      pass          1.000  10
--   4      stage         1.000  00
--   5      pass          1.000  10
--   6      reset         1.000  11
--   7      pass          1.000  10
-- Jev microcode ROM `e0_0_route_x`: controller state -> Jev's answer -> select code (LSB first: rom_82 rom_83)
--   state  answer        p      code
--   0      x0            1.000  00
--   1      x1            1.000  01
--   2      x2            1.000  10
--   3      x3            1.000  11
-- Jev microcode ROM `e0_0_route_w`: controller state -> Jev's answer -> select code (LSB first: rom_84 rom_85)
--   state  answer        p      code
--   0      w0            1.000  00
--   1      w1            1.000  01
--   2      w2            1.000  10
--   3      w3            1.000  11
-- Jev microcode ROM `e0_0_mac_op`: controller state -> Jev's answer -> select code (LSB first: rom_86)
--   state  answer        p      code
--   0      mac           1.000  1
--   1      mac           1.000  1
--   2      mac           1.000  1
--   3      mac           1.000  1
-- Jev microcode ROM `e0_1_route_x`: controller state -> Jev's answer -> select code (LSB first: rom_155 rom_156)
--   state  answer        p      code
--   0      x0            1.000  00
--   1      x1            1.000  01
--   2      x2            1.000  10
--   3      x3            1.000  11
-- Jev microcode ROM `e0_1_route_w`: controller state -> Jev's answer -> select code (LSB first: rom_157 rom_158)
--   state  answer        p      code
--   0      w0            1.000  00
--   1      w1            1.000  01
--   2      w2            1.000  10
--   3      w3            1.000  11
-- Jev microcode ROM `e0_1_mac_op`: controller state -> Jev's answer -> select code (LSB first: rom_159)
--   state  answer        p      code
--   0      mac           1.000  1
--   1      mac           1.000  1
--   2      mac           1.000  1
--   3      mac           1.000  1
-- Jev microcode ROM `e1_0_route_x`: controller state -> Jev's answer -> select code (LSB first: rom_228 rom_229)
--   state  answer        p      code
--   0      x0            1.000  00
--   1      x1            1.000  01
--   2      x2            1.000  10
--   3      x3            1.000  11
-- Jev microcode ROM `e1_0_route_w`: controller state -> Jev's answer -> select code (LSB first: rom_230 rom_231)
--   state  answer        p      code
--   0      w0            1.000  00
--   1      w1            1.000  01
--   2      w2            1.000  10
--   3      w3            1.000  11
-- Jev microcode ROM `e1_0_mac_op`: controller state -> Jev's answer -> select code (LSB first: rom_232)
--   state  answer        p      code
--   0      mac           1.000  1
--   1      mac           1.000  1
--   2      mac           1.000  1
--   3      mac           1.000  1
-- Jev microcode ROM `e1_1_route_x`: controller state -> Jev's answer -> select code (LSB first: rom_301 rom_302)
--   state  answer        p      code
--   0      x0            1.000  00
--   1      x1            1.000  01
--   2      x2            1.000  10
--   3      x3            1.000  11
-- Jev microcode ROM `e1_1_route_w`: controller state -> Jev's answer -> select code (LSB first: rom_303 rom_304)
--   state  answer        p      code
--   0      w0            1.000  00
--   1      w1            1.000  01
--   2      w2            1.000  10
--   3      w3            1.000  11
-- Jev microcode ROM `e1_1_mac_op`: controller state -> Jev's answer -> select code (LSB first: rom_305)
--   state  answer        p      code
--   0      mac           1.000  1
--   1      mac           1.000  1
--   2      mac           1.000  1
--   3      mac           1.000  1
-- Jev microcode ROM `jev_accept`: controller state -> Jev's answer -> select code (LSB first: rom_361)
--   state  answer        p      code
--   0      stall         1.000  0
--   1      take          1.000  1
--   2      stall         1.000  0
--   3      stall         1.000  0
--   4      stall         1.000  0
--   5      take          1.000  1
--   6      take          1.000  1
--   7      take          1.000  1
--   8      stall         1.000  0
--   9      take          1.000  1
--   10     stall         1.000  0
--   11     stall         1.000  0
--   12     take          1.000  1
--   13     take          1.000  1
--   14     take          1.000  1
--   15     take          1.000  1
-- Jev microcode ROM `jev_join`: controller state -> Jev's answer -> select code (LSB first: rom_551)
--   state  answer        p      code
--   0      hold          1.000  0
--   1      hold          1.000  0
--   2      hold          1.000  0
--   3      hold          1.000  0
--   4      hold          1.000  0
--   5      hold          1.000  0
--   6      hold          1.000  0
--   7      emit          1.000  1

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity jev_mesh_2x2 is
  port (
    clk : in std_logic;
    rst : in std_logic;
    n_valid : in std_logic;
    n_kind : in std_logic_vector(1 downto 0);
    n_d0 : in unsigned(31 downto 0);
    n_d1 : in unsigned(31 downto 0);
    s_ready : in std_logic;
    w_valid : in std_logic;
    w_p0 : in unsigned(31 downto 0);
    w_p1 : in unsigned(31 downto 0);
    e_ready : in std_logic;
    n_ready : out std_logic;
    s_valid : out std_logic;
    s_kind : out std_logic_vector(1 downto 0);
    s_d0 : out unsigned(31 downto 0);
    s_d1 : out unsigned(31 downto 0);
    w_ready : out std_logic;
    e_valid : out std_logic;
    e_p0 : out unsigned(31 downto 0);
    e_p1 : out unsigned(31 downto 0)
  );
end entity jev_mesh_2x2;

architecture fabric of jev_mesh_2x2 is
  -- a LUT4 cell: row (d c b a) of truth table t
  function lut4(f_t : std_logic_vector(15 downto 0); f_d, f_c, f_b, f_a : std_logic) return std_logic is
  begin
    return f_t(to_integer(unsigned'(f_d & f_c & f_b & f_a)));
  end function;
  signal wcnt_0 : std_logic := '0';
  signal wcnt_1 : std_logic := '0';
  signal wcnt_2 : std_logic := '0';
  signal wcnt_3 : std_logic := '0';
  signal akcnt_0 : std_logic := '0';
  signal akcnt_1 : std_logic := '0';
  signal pend : std_logic := '0';
  signal xs0_0 : unsigned(31 downto 0) := x"00000000";
  signal xa0_0 : unsigned(31 downto 0) := x"00000000";
  signal xs0_1 : unsigned(31 downto 0) := x"00000000";
  signal xa0_1 : unsigned(31 downto 0) := x"00000000";
  signal xs0_2 : unsigned(31 downto 0) := x"00000000";
  signal xa0_2 : unsigned(31 downto 0) := x"00000000";
  signal xs0_3 : unsigned(31 downto 0) := x"00000000";
  signal xa0_3 : unsigned(31 downto 0) := x"00000000";
  signal xs1_0 : unsigned(31 downto 0) := x"00000000";
  signal xa1_0 : unsigned(31 downto 0) := x"00000000";
  signal xs1_1 : unsigned(31 downto 0) := x"00000000";
  signal xa1_1 : unsigned(31 downto 0) := x"00000000";
  signal xs1_2 : unsigned(31 downto 0) := x"00000000";
  signal xa1_2 : unsigned(31 downto 0) := x"00000000";
  signal xs1_3 : unsigned(31 downto 0) := x"00000000";
  signal xa1_3 : unsigned(31 downto 0) := x"00000000";
  signal wt0 : unsigned(31 downto 0) := x"00000000";
  signal wt1 : unsigned(31 downto 0) := x"00000000";
  signal wt2 : unsigned(31 downto 0) := x"00000000";
  signal wt3 : unsigned(31 downto 0) := x"00000000";
  signal wt4 : unsigned(31 downto 0) := x"00000000";
  signal wt5 : unsigned(31 downto 0) := x"00000000";
  signal wt6 : unsigned(31 downto 0) := x"00000000";
  signal wt7 : unsigned(31 downto 0) := x"00000000";
  signal wt8 : unsigned(31 downto 0) := x"00000000";
  signal wt9 : unsigned(31 downto 0) := x"00000000";
  signal wt10 : unsigned(31 downto 0) := x"00000000";
  signal wt11 : unsigned(31 downto 0) := x"00000000";
  signal wt12 : unsigned(31 downto 0) := x"00000000";
  signal wt13 : unsigned(31 downto 0) := x"00000000";
  signal wt14 : unsigned(31 downto 0) := x"00000000";
  signal wt15 : unsigned(31 downto 0) := x"00000000";
  signal e0_0_state_0 : std_logic := '0';
  signal e0_0_state_1 : std_logic := '0';
  signal e0_0_o_valid : std_logic := '0';
  signal e0_0_o_mac : std_logic := '0';
  signal e0_0_o_last : std_logic := '0';
  signal e0_0_s_valid : std_logic := '0';
  signal e0_0_s_mac : std_logic := '0';
  signal e0_0_s_last : std_logic := '0';
  signal e0_0_r_valid : std_logic := '0';
  signal e0_0_o_p : unsigned(31 downto 0) := x"00000000";
  signal e0_0_s_p : unsigned(31 downto 0) := x"00000000";
  signal e0_0_acc : unsigned(31 downto 0) := x"00000000";
  signal e0_0_res : unsigned(31 downto 0) := x"00000000";
  signal e0_0_a_valid : std_logic := '0';
  signal e0_0_a_mac : std_logic := '0';
  signal e0_0_a_last : std_logic := '0';
  signal e0_0_a_x : unsigned(31 downto 0) := x"00000000";
  signal e0_0_a_w : unsigned(31 downto 0) := x"00000000";
  signal e0_1_state_0 : std_logic := '0';
  signal e0_1_state_1 : std_logic := '0';
  signal e0_1_o_valid : std_logic := '0';
  signal e0_1_o_mac : std_logic := '0';
  signal e0_1_o_last : std_logic := '0';
  signal e0_1_s_valid : std_logic := '0';
  signal e0_1_s_mac : std_logic := '0';
  signal e0_1_s_last : std_logic := '0';
  signal e0_1_r_valid : std_logic := '0';
  signal e0_1_o_p : unsigned(31 downto 0) := x"00000000";
  signal e0_1_s_p : unsigned(31 downto 0) := x"00000000";
  signal e0_1_acc : unsigned(31 downto 0) := x"00000000";
  signal e0_1_res : unsigned(31 downto 0) := x"00000000";
  signal e0_1_a_valid : std_logic := '0';
  signal e0_1_a_mac : std_logic := '0';
  signal e0_1_a_last : std_logic := '0';
  signal e0_1_a_x : unsigned(31 downto 0) := x"00000000";
  signal e0_1_a_w : unsigned(31 downto 0) := x"00000000";
  signal e1_0_state_0 : std_logic := '0';
  signal e1_0_state_1 : std_logic := '0';
  signal e1_0_o_valid : std_logic := '0';
  signal e1_0_o_mac : std_logic := '0';
  signal e1_0_o_last : std_logic := '0';
  signal e1_0_s_valid : std_logic := '0';
  signal e1_0_s_mac : std_logic := '0';
  signal e1_0_s_last : std_logic := '0';
  signal e1_0_r_valid : std_logic := '0';
  signal e1_0_o_p : unsigned(31 downto 0) := x"00000000";
  signal e1_0_s_p : unsigned(31 downto 0) := x"00000000";
  signal e1_0_acc : unsigned(31 downto 0) := x"00000000";
  signal e1_0_res : unsigned(31 downto 0) := x"00000000";
  signal e1_0_a_valid : std_logic := '0';
  signal e1_0_a_mac : std_logic := '0';
  signal e1_0_a_last : std_logic := '0';
  signal e1_0_a_x : unsigned(31 downto 0) := x"00000000";
  signal e1_0_a_w : unsigned(31 downto 0) := x"00000000";
  signal e1_1_state_0 : std_logic := '0';
  signal e1_1_state_1 : std_logic := '0';
  signal e1_1_o_valid : std_logic := '0';
  signal e1_1_o_mac : std_logic := '0';
  signal e1_1_o_last : std_logic := '0';
  signal e1_1_s_valid : std_logic := '0';
  signal e1_1_s_mac : std_logic := '0';
  signal e1_1_s_last : std_logic := '0';
  signal e1_1_r_valid : std_logic := '0';
  signal e1_1_o_p : unsigned(31 downto 0) := x"00000000";
  signal e1_1_s_p : unsigned(31 downto 0) := x"00000000";
  signal e1_1_acc : unsigned(31 downto 0) := x"00000000";
  signal e1_1_res : unsigned(31 downto 0) := x"00000000";
  signal e1_1_a_valid : std_logic := '0';
  signal e1_1_a_mac : std_logic := '0';
  signal e1_1_a_last : std_logic := '0';
  signal e1_1_a_x : unsigned(31 downto 0) := x"00000000";
  signal e1_1_a_w : unsigned(31 downto 0) := x"00000000";
  signal s_hv : std_logic := '0';
  signal s_tv : std_logic := '0';
  signal s_h0 : unsigned(31 downto 0) := x"00000000";
  signal s_t0 : unsigned(31 downto 0) := x"00000000";
  signal s_h1 : unsigned(31 downto 0) := x"00000000";
  signal s_t1 : unsigned(31 downto 0) := x"00000000";
  signal s_h2 : unsigned(31 downto 0) := x"00000000";
  signal s_t2 : unsigned(31 downto 0) := x"00000000";
  signal s_h3 : unsigned(31 downto 0) := x"00000000";
  signal s_t3 : unsigned(31 downto 0) := x"00000000";
  signal s_hb0 : std_logic := '0';
  signal s_tb0 : std_logic := '0';
  signal s_hb1 : std_logic := '0';
  signal s_tb1 : std_logic := '0';
  signal e_hv : std_logic := '0';
  signal e_tv : std_logic := '0';
  signal e_h0 : unsigned(31 downto 0) := x"00000000";
  signal e_t0 : unsigned(31 downto 0) := x"00000000";
  signal e_h1 : unsigned(31 downto 0) := x"00000000";
  signal e_t1 : unsigned(31 downto 0) := x"00000000";
  signal e_h2 : unsigned(31 downto 0) := x"00000000";
  signal e_t2 : unsigned(31 downto 0) := x"00000000";
  signal xnor_16 : std_logic;
  signal xnor_17 : std_logic;
  signal xnor_18 : std_logic;
  signal xnor_19 : std_logic;
  signal xnor_28 : std_logic;
  signal xnor_29 : std_logic;
  signal rom_82 : std_logic;
  signal rom_83 : std_logic;
  signal rom_84 : std_logic;
  signal rom_85 : std_logic;
  signal rom_86 : std_logic;
  signal xnor_87 : std_logic;
  signal xnor_88 : std_logic;
  signal nand_90 : std_logic;
  signal xor3_92 : std_logic;
  signal maj_93 : std_logic;
  signal pe3_110 : unsigned(31 downto 0);
  signal not_111 : std_logic;
  signal pe1_129 : unsigned(31 downto 0);
  signal k_132 : unsigned(31 downto 0);
  signal rom_155 : std_logic;
  signal rom_156 : std_logic;
  signal rom_157 : std_logic;
  signal rom_158 : std_logic;
  signal rom_159 : std_logic;
  signal xnor_160 : std_logic;
  signal xnor_161 : std_logic;
  signal nand_163 : std_logic;
  signal xor3_165 : std_logic;
  signal maj_166 : std_logic;
  signal pe3_183 : unsigned(31 downto 0);
  signal not_184 : std_logic;
  signal pe1_202 : unsigned(31 downto 0);
  signal k_205 : unsigned(31 downto 0);
  signal rom_228 : std_logic;
  signal rom_229 : std_logic;
  signal rom_230 : std_logic;
  signal rom_231 : std_logic;
  signal rom_232 : std_logic;
  signal xnor_233 : std_logic;
  signal xnor_234 : std_logic;
  signal nand_236 : std_logic;
  signal xor3_238 : std_logic;
  signal maj_239 : std_logic;
  signal pe3_256 : unsigned(31 downto 0);
  signal not_257 : std_logic;
  signal pe1_275 : unsigned(31 downto 0);
  signal k_278 : unsigned(31 downto 0);
  signal rom_301 : std_logic;
  signal rom_302 : std_logic;
  signal rom_303 : std_logic;
  signal rom_304 : std_logic;
  signal rom_305 : std_logic;
  signal xnor_306 : std_logic;
  signal xnor_307 : std_logic;
  signal nand_309 : std_logic;
  signal xor3_311 : std_logic;
  signal maj_312 : std_logic;
  signal pe3_329 : unsigned(31 downto 0);
  signal not_330 : std_logic;
  signal pe1_348 : unsigned(31 downto 0);
  signal k_351 : unsigned(31 downto 0);
  signal not_356 : std_logic;
  signal xnor_369 : std_logic;
  signal xnor_370 : std_logic;
  signal xnor_371 : std_logic;
  signal xnor_372 : std_logic;
  signal xnor_377 : std_logic;
  signal xnor_378 : std_logic;
  signal xnor_379 : std_logic;
  signal xnor_380 : std_logic;
  signal xnor_385 : std_logic;
  signal xnor_386 : std_logic;
  signal xnor_387 : std_logic;
  signal xnor_388 : std_logic;
  signal xnor_393 : std_logic;
  signal xnor_394 : std_logic;
  signal xnor_395 : std_logic;
  signal xnor_396 : std_logic;
  signal xnor_401 : std_logic;
  signal xnor_402 : std_logic;
  signal xnor_403 : std_logic;
  signal xnor_404 : std_logic;
  signal xnor_409 : std_logic;
  signal xnor_410 : std_logic;
  signal xnor_411 : std_logic;
  signal xnor_412 : std_logic;
  signal xnor_417 : std_logic;
  signal xnor_418 : std_logic;
  signal xnor_419 : std_logic;
  signal xnor_420 : std_logic;
  signal xnor_425 : std_logic;
  signal xnor_426 : std_logic;
  signal xnor_427 : std_logic;
  signal xnor_428 : std_logic;
  signal xor3_433 : std_logic;
  signal maj_434 : std_logic;
  signal xnor_449 : std_logic;
  signal xnor_450 : std_logic;
  signal xnor_454 : std_logic;
  signal xnor_455 : std_logic;
  signal xnor_459 : std_logic;
  signal xnor_460 : std_logic;
  signal xnor_464 : std_logic;
  signal xnor_465 : std_logic;
  signal xnor_469 : std_logic;
  signal xnor_470 : std_logic;
  signal xnor_474 : std_logic;
  signal xnor_475 : std_logic;
  signal xnor_479 : std_logic;
  signal xnor_480 : std_logic;
  signal xnor_484 : std_logic;
  signal xnor_485 : std_logic;
  signal xor3_489 : std_logic;
  signal maj_490 : std_logic;
  signal k_505 : unsigned(31 downto 0);
  signal k_506 : unsigned(31 downto 0);
  signal and_509 : std_logic;
  signal not_545 : std_logic;
  signal pe1_546 : unsigned(31 downto 0);
  signal pe1_548 : unsigned(31 downto 0);
  signal k_552 : unsigned(31 downto 0);
  signal and_555 : std_logic;
  signal not_576 : std_logic;
  signal and4_20 : std_logic;
  signal and4_30 : std_logic;
  signal and4_89 : std_logic;
  signal and_91 : std_logic;
  signal xor3_94 : std_logic;
  signal maj_95 : std_logic;
  signal sel_99 : unsigned(31 downto 0);
  signal sel_100 : unsigned(31 downto 0);
  signal sel_103 : unsigned(31 downto 0);
  signal sel_104 : unsigned(31 downto 0);
  signal and_112 : std_logic;
  signal sel_130 : unsigned(31 downto 0);
  signal and4_162 : std_logic;
  signal and_164 : std_logic;
  signal xor3_167 : std_logic;
  signal maj_168 : std_logic;
  signal sel_172 : unsigned(31 downto 0);
  signal sel_173 : unsigned(31 downto 0);
  signal sel_176 : unsigned(31 downto 0);
  signal sel_177 : unsigned(31 downto 0);
  signal and_185 : std_logic;
  signal sel_203 : unsigned(31 downto 0);
  signal and4_235 : std_logic;
  signal and_237 : std_logic;
  signal xor3_240 : std_logic;
  signal maj_241 : std_logic;
  signal sel_245 : unsigned(31 downto 0);
  signal sel_246 : unsigned(31 downto 0);
  signal sel_249 : unsigned(31 downto 0);
  signal sel_250 : unsigned(31 downto 0);
  signal and_258 : std_logic;
  signal sel_276 : unsigned(31 downto 0);
  signal and4_308 : std_logic;
  signal and_310 : std_logic;
  signal xor3_313 : std_logic;
  signal maj_314 : std_logic;
  signal sel_318 : unsigned(31 downto 0);
  signal sel_319 : unsigned(31 downto 0);
  signal sel_322 : unsigned(31 downto 0);
  signal sel_323 : unsigned(31 downto 0);
  signal and_331 : std_logic;
  signal sel_349 : unsigned(31 downto 0);
  signal and4_373 : std_logic;
  signal and4_381 : std_logic;
  signal and4_389 : std_logic;
  signal and4_397 : std_logic;
  signal and4_405 : std_logic;
  signal and4_413 : std_logic;
  signal and4_421 : std_logic;
  signal and4_429 : std_logic;
  signal xor3_435 : std_logic;
  signal maj_436 : std_logic;
  signal and4_451 : std_logic;
  signal and4_456 : std_logic;
  signal and4_461 : std_logic;
  signal and4_466 : std_logic;
  signal and4_471 : std_logic;
  signal and4_476 : std_logic;
  signal and4_481 : std_logic;
  signal and4_486 : std_logic;
  signal xor3_491 : std_logic;
  signal maj_492 : std_logic;
  signal and_511 : std_logic;
  signal pe1_547 : unsigned(31 downto 0);
  signal pe1_549 : unsigned(31 downto 0);
  signal rom_551 : std_logic;
  signal and_557 : std_logic;
  signal rom_21 : std_logic;
  signal rom_22 : std_logic;
  signal mux_96 : std_logic;
  signal mux_97 : std_logic;
  signal and_98 : std_logic;
  signal sel_101 : unsigned(31 downto 0);
  signal sel_105 : unsigned(31 downto 0);
  signal mux_107 : std_logic;
  signal mux_108 : std_logic;
  signal a_valid_next_109 : std_logic;
  signal acc_ready_113 : std_logic;
  signal sel_133 : unsigned(31 downto 0);
  signal mux_169 : std_logic;
  signal mux_170 : std_logic;
  signal and_171 : std_logic;
  signal sel_174 : unsigned(31 downto 0);
  signal sel_178 : unsigned(31 downto 0);
  signal mux_180 : std_logic;
  signal mux_181 : std_logic;
  signal a_valid_next_182 : std_logic;
  signal acc_ready_186 : std_logic;
  signal sel_206 : unsigned(31 downto 0);
  signal mux_242 : std_logic;
  signal mux_243 : std_logic;
  signal and_244 : std_logic;
  signal sel_247 : unsigned(31 downto 0);
  signal sel_251 : unsigned(31 downto 0);
  signal mux_253 : std_logic;
  signal mux_254 : std_logic;
  signal a_valid_next_255 : std_logic;
  signal acc_ready_259 : std_logic;
  signal sel_279 : unsigned(31 downto 0);
  signal mux_315 : std_logic;
  signal mux_316 : std_logic;
  signal and_317 : std_logic;
  signal sel_320 : unsigned(31 downto 0);
  signal sel_324 : unsigned(31 downto 0);
  signal mux_326 : std_logic;
  signal mux_327 : std_logic;
  signal a_valid_next_328 : std_logic;
  signal acc_ready_332 : std_logic;
  signal sel_352 : unsigned(31 downto 0);
  signal not_358 : std_logic;
  signal xor3_437 : std_logic;
  signal maj_438 : std_logic;
  signal link_hin_556 : std_logic;
  signal link_tin_558 : std_logic;
  signal link_hv_559 : std_logic;
  signal link_tv_560 : std_logic;
  signal act_dec_23 : std_logic;
  signal act_dec_24 : std_logic;
  signal sel_102 : unsigned(31 downto 0);
  signal sel_106 : unsigned(31 downto 0);
  signal and_114 : std_logic;
  signal sel_175 : unsigned(31 downto 0);
  signal sel_179 : unsigned(31 downto 0);
  signal and_187 : std_logic;
  signal sel_248 : unsigned(31 downto 0);
  signal sel_252 : unsigned(31 downto 0);
  signal and_260 : std_logic;
  signal sel_321 : unsigned(31 downto 0);
  signal sel_325 : unsigned(31 downto 0);
  signal and_333 : std_logic;
  signal or_357 : std_logic;
  signal act_dec_365 : std_logic;
  signal xor3_439 : std_logic;
  signal maj_440 : std_logic;
  signal sel_563 : unsigned(31 downto 0);
  signal sel_564 : unsigned(31 downto 0);
  signal sel_568 : unsigned(31 downto 0);
  signal sel_569 : unsigned(31 downto 0);
  signal sel_573 : unsigned(31 downto 0);
  signal sel_574 : unsigned(31 downto 0);
  signal and_115 : std_logic;
  signal o_take_116 : std_logic;
  signal s_take_117 : std_logic;
  signal and_131 : std_logic;
  signal sel_134 : unsigned(31 downto 0);
  signal and_188 : std_logic;
  signal o_take_189 : std_logic;
  signal s_take_190 : std_logic;
  signal and_204 : std_logic;
  signal sel_207 : unsigned(31 downto 0);
  signal and_261 : std_logic;
  signal o_take_262 : std_logic;
  signal s_take_263 : std_logic;
  signal and_277 : std_logic;
  signal sel_280 : unsigned(31 downto 0);
  signal and_334 : std_logic;
  signal o_take_335 : std_logic;
  signal s_take_336 : std_logic;
  signal and_350 : std_logic;
  signal sel_353 : unsigned(31 downto 0);
  signal or_359 : std_logic;
  signal not_367 : std_logic;
  signal sel_565 : unsigned(31 downto 0);
  signal sel_570 : unsigned(31 downto 0);
  signal sel_575 : unsigned(31 downto 0);
  signal o_valid_next_118 : std_logic;
  signal sel_119 : unsigned(31 downto 0);
  signal mux_121 : std_logic;
  signal mux_123 : std_logic;
  signal s_valid_next_125 : std_logic;
  signal sel_126 : unsigned(31 downto 0);
  signal mux_127 : std_logic;
  signal mux_128 : std_logic;
  signal sel_135 : unsigned(31 downto 0);
  signal r_valid_next_136 : std_logic;
  signal o_valid_next_191 : std_logic;
  signal sel_192 : unsigned(31 downto 0);
  signal mux_194 : std_logic;
  signal mux_196 : std_logic;
  signal s_valid_next_198 : std_logic;
  signal sel_199 : unsigned(31 downto 0);
  signal mux_200 : std_logic;
  signal mux_201 : std_logic;
  signal sel_208 : unsigned(31 downto 0);
  signal r_valid_next_209 : std_logic;
  signal o_valid_next_264 : std_logic;
  signal sel_265 : unsigned(31 downto 0);
  signal mux_267 : std_logic;
  signal mux_269 : std_logic;
  signal s_valid_next_271 : std_logic;
  signal sel_272 : unsigned(31 downto 0);
  signal mux_273 : std_logic;
  signal mux_274 : std_logic;
  signal sel_281 : unsigned(31 downto 0);
  signal r_valid_next_282 : std_logic;
  signal o_valid_next_337 : std_logic;
  signal sel_338 : unsigned(31 downto 0);
  signal mux_340 : std_logic;
  signal mux_342 : std_logic;
  signal s_valid_next_344 : std_logic;
  signal sel_345 : unsigned(31 downto 0);
  signal mux_346 : std_logic;
  signal mux_347 : std_logic;
  signal sel_354 : unsigned(31 downto 0);
  signal r_valid_next_355 : std_logic;
  signal rom_361 : std_logic;
  signal sel_120 : unsigned(31 downto 0);
  signal mux_122 : std_logic;
  signal mux_124 : std_logic;
  signal sel_193 : unsigned(31 downto 0);
  signal mux_195 : std_logic;
  signal mux_197 : std_logic;
  signal sel_266 : unsigned(31 downto 0);
  signal mux_268 : std_logic;
  signal mux_270 : std_logic;
  signal sel_339 : unsigned(31 downto 0);
  signal mux_341 : std_logic;
  signal mux_343 : std_logic;
  signal and_362 : std_logic;
  signal and_363 : std_logic;
  signal and_364 : std_logic;
  signal and_366 : std_logic;
  signal and_368 : std_logic;
  signal and_374 : std_logic;
  signal and_382 : std_logic;
  signal and_390 : std_logic;
  signal and_398 : std_logic;
  signal and_406 : std_logic;
  signal and_414 : std_logic;
  signal and_422 : std_logic;
  signal and_430 : std_logic;
  signal mux_441 : std_logic;
  signal mux_442 : std_logic;
  signal mux_443 : std_logic;
  signal mux_444 : std_logic;
  signal and_452 : std_logic;
  signal and_457 : std_logic;
  signal and_462 : std_logic;
  signal and_467 : std_logic;
  signal and_472 : std_logic;
  signal and_477 : std_logic;
  signal and_482 : std_logic;
  signal and_487 : std_logic;
  signal mux_493 : std_logic;
  signal mux_494 : std_logic;
  signal and_495 : std_logic;
  signal link_hin_510 : std_logic;
  signal link_tin_512 : std_logic;
  signal link_hv_513 : std_logic;
  signal link_tv_514 : std_logic;
  signal sel_375 : unsigned(31 downto 0);
  signal sel_376 : unsigned(31 downto 0);
  signal sel_383 : unsigned(31 downto 0);
  signal sel_384 : unsigned(31 downto 0);
  signal sel_391 : unsigned(31 downto 0);
  signal sel_392 : unsigned(31 downto 0);
  signal sel_399 : unsigned(31 downto 0);
  signal sel_400 : unsigned(31 downto 0);
  signal sel_407 : unsigned(31 downto 0);
  signal sel_408 : unsigned(31 downto 0);
  signal sel_415 : unsigned(31 downto 0);
  signal sel_416 : unsigned(31 downto 0);
  signal sel_423 : unsigned(31 downto 0);
  signal sel_424 : unsigned(31 downto 0);
  signal sel_431 : unsigned(31 downto 0);
  signal sel_432 : unsigned(31 downto 0);
  signal mux_445 : std_logic;
  signal mux_446 : std_logic;
  signal mux_447 : std_logic;
  signal mux_448 : std_logic;
  signal sel_453 : unsigned(31 downto 0);
  signal sel_458 : unsigned(31 downto 0);
  signal sel_463 : unsigned(31 downto 0);
  signal sel_468 : unsigned(31 downto 0);
  signal sel_473 : unsigned(31 downto 0);
  signal sel_478 : unsigned(31 downto 0);
  signal sel_483 : unsigned(31 downto 0);
  signal sel_488 : unsigned(31 downto 0);
  signal pend_next_504 : std_logic;
  signal sel_517 : unsigned(31 downto 0);
  signal sel_518 : unsigned(31 downto 0);
  signal sel_522 : unsigned(31 downto 0);
  signal sel_523 : unsigned(31 downto 0);
  signal sel_527 : unsigned(31 downto 0);
  signal sel_528 : unsigned(31 downto 0);
  signal sel_532 : unsigned(31 downto 0);
  signal sel_533 : unsigned(31 downto 0);
  signal mux_537 : std_logic;
  signal mux_538 : std_logic;
  signal mux_542 : std_logic;
  signal mux_543 : std_logic;
  signal sel_496 : unsigned(31 downto 0);
  signal sel_497 : unsigned(31 downto 0);
  signal sel_498 : unsigned(31 downto 0);
  signal sel_499 : unsigned(31 downto 0);
  signal sel_500 : unsigned(31 downto 0);
  signal sel_501 : unsigned(31 downto 0);
  signal sel_502 : unsigned(31 downto 0);
  signal sel_503 : unsigned(31 downto 0);
  signal sel_519 : unsigned(31 downto 0);
  signal sel_524 : unsigned(31 downto 0);
  signal sel_529 : unsigned(31 downto 0);
  signal sel_534 : unsigned(31 downto 0);
  signal mux_539 : std_logic;
  signal mux_544 : std_logic;
begin
  -- level 0
  xnor_16 <= lut4(x"9999", '0', '0', '0', wcnt_0);
  xnor_17 <= lut4(x"9999", '0', '0', '0', wcnt_1);
  xnor_18 <= lut4(x"9999", '0', '0', '0', wcnt_2);
  xnor_19 <= lut4(x"9999", '0', '0', '1', wcnt_3);
  xnor_28 <= lut4(x"9999", '0', '0', '1', akcnt_0);
  xnor_29 <= lut4(x"9999", '0', '0', '1', akcnt_1);
  rom_82 <= lut4(x"AAAA", '0', '0', e0_0_state_1, e0_0_state_0);
  rom_83 <= lut4(x"CCCC", '0', '0', e0_0_state_1, e0_0_state_0);
  rom_84 <= lut4(x"AAAA", '0', '0', e0_0_state_1, e0_0_state_0);
  rom_85 <= lut4(x"CCCC", '0', '0', e0_0_state_1, e0_0_state_0);
  rom_86 <= lut4(x"FFFF", '0', '0', e0_0_state_1, e0_0_state_0);
  xnor_87 <= lut4(x"9999", '0', '0', '1', e0_0_state_0);
  xnor_88 <= lut4(x"9999", '0', '0', '1', e0_0_state_1);
  nand_90 <= lut4(x"7777", '0', '0', e0_0_s_valid, e0_0_a_valid);
  xor3_92 <= lut4(x"9696", '0', '0', '1', e0_0_state_0);
  maj_93 <= lut4(x"E8E8", '0', '0', '1', e0_0_state_0);
  pe3_110 <= resize(e0_0_a_x * e0_0_a_w, 32);
  not_111 <= lut4(x"5555", '0', '0', '0', e0_0_s_valid);
  pe1_129 <= e0_0_acc + e0_0_o_p;
  k_132 <= unsigned'(x"00000000");
  rom_155 <= lut4(x"AAAA", '0', '0', e0_1_state_1, e0_1_state_0);
  rom_156 <= lut4(x"CCCC", '0', '0', e0_1_state_1, e0_1_state_0);
  rom_157 <= lut4(x"AAAA", '0', '0', e0_1_state_1, e0_1_state_0);
  rom_158 <= lut4(x"CCCC", '0', '0', e0_1_state_1, e0_1_state_0);
  rom_159 <= lut4(x"FFFF", '0', '0', e0_1_state_1, e0_1_state_0);
  xnor_160 <= lut4(x"9999", '0', '0', '1', e0_1_state_0);
  xnor_161 <= lut4(x"9999", '0', '0', '1', e0_1_state_1);
  nand_163 <= lut4(x"7777", '0', '0', e0_1_s_valid, e0_1_a_valid);
  xor3_165 <= lut4(x"9696", '0', '0', '1', e0_1_state_0);
  maj_166 <= lut4(x"E8E8", '0', '0', '1', e0_1_state_0);
  pe3_183 <= resize(e0_1_a_x * e0_1_a_w, 32);
  not_184 <= lut4(x"5555", '0', '0', '0', e0_1_s_valid);
  pe1_202 <= e0_1_acc + e0_1_o_p;
  k_205 <= unsigned'(x"00000000");
  rom_228 <= lut4(x"AAAA", '0', '0', e1_0_state_1, e1_0_state_0);
  rom_229 <= lut4(x"CCCC", '0', '0', e1_0_state_1, e1_0_state_0);
  rom_230 <= lut4(x"AAAA", '0', '0', e1_0_state_1, e1_0_state_0);
  rom_231 <= lut4(x"CCCC", '0', '0', e1_0_state_1, e1_0_state_0);
  rom_232 <= lut4(x"FFFF", '0', '0', e1_0_state_1, e1_0_state_0);
  xnor_233 <= lut4(x"9999", '0', '0', '1', e1_0_state_0);
  xnor_234 <= lut4(x"9999", '0', '0', '1', e1_0_state_1);
  nand_236 <= lut4(x"7777", '0', '0', e1_0_s_valid, e1_0_a_valid);
  xor3_238 <= lut4(x"9696", '0', '0', '1', e1_0_state_0);
  maj_239 <= lut4(x"E8E8", '0', '0', '1', e1_0_state_0);
  pe3_256 <= resize(e1_0_a_x * e1_0_a_w, 32);
  not_257 <= lut4(x"5555", '0', '0', '0', e1_0_s_valid);
  pe1_275 <= e1_0_acc + e1_0_o_p;
  k_278 <= unsigned'(x"00000000");
  rom_301 <= lut4(x"AAAA", '0', '0', e1_1_state_1, e1_1_state_0);
  rom_302 <= lut4(x"CCCC", '0', '0', e1_1_state_1, e1_1_state_0);
  rom_303 <= lut4(x"AAAA", '0', '0', e1_1_state_1, e1_1_state_0);
  rom_304 <= lut4(x"CCCC", '0', '0', e1_1_state_1, e1_1_state_0);
  rom_305 <= lut4(x"FFFF", '0', '0', e1_1_state_1, e1_1_state_0);
  xnor_306 <= lut4(x"9999", '0', '0', '1', e1_1_state_0);
  xnor_307 <= lut4(x"9999", '0', '0', '1', e1_1_state_1);
  nand_309 <= lut4(x"7777", '0', '0', e1_1_s_valid, e1_1_a_valid);
  xor3_311 <= lut4(x"9696", '0', '0', '1', e1_1_state_0);
  maj_312 <= lut4(x"E8E8", '0', '0', '1', e1_1_state_0);
  pe3_329 <= resize(e1_1_a_x * e1_1_a_w, 32);
  not_330 <= lut4(x"5555", '0', '0', '0', e1_1_s_valid);
  pe1_348 <= e1_1_acc + e1_1_o_p;
  k_351 <= unsigned'(x"00000000");
  not_356 <= lut4(x"5555", '0', '0', '0', pend);
  xnor_369 <= lut4(x"9999", '0', '0', '0', wcnt_0);
  xnor_370 <= lut4(x"9999", '0', '0', '0', wcnt_1);
  xnor_371 <= lut4(x"9999", '0', '0', '0', wcnt_2);
  xnor_372 <= lut4(x"9999", '0', '0', '0', wcnt_3);
  xnor_377 <= lut4(x"9999", '0', '0', '1', wcnt_0);
  xnor_378 <= lut4(x"9999", '0', '0', '0', wcnt_1);
  xnor_379 <= lut4(x"9999", '0', '0', '0', wcnt_2);
  xnor_380 <= lut4(x"9999", '0', '0', '0', wcnt_3);
  xnor_385 <= lut4(x"9999", '0', '0', '0', wcnt_0);
  xnor_386 <= lut4(x"9999", '0', '0', '1', wcnt_1);
  xnor_387 <= lut4(x"9999", '0', '0', '0', wcnt_2);
  xnor_388 <= lut4(x"9999", '0', '0', '0', wcnt_3);
  xnor_393 <= lut4(x"9999", '0', '0', '1', wcnt_0);
  xnor_394 <= lut4(x"9999", '0', '0', '1', wcnt_1);
  xnor_395 <= lut4(x"9999", '0', '0', '0', wcnt_2);
  xnor_396 <= lut4(x"9999", '0', '0', '0', wcnt_3);
  xnor_401 <= lut4(x"9999", '0', '0', '0', wcnt_0);
  xnor_402 <= lut4(x"9999", '0', '0', '0', wcnt_1);
  xnor_403 <= lut4(x"9999", '0', '0', '1', wcnt_2);
  xnor_404 <= lut4(x"9999", '0', '0', '0', wcnt_3);
  xnor_409 <= lut4(x"9999", '0', '0', '1', wcnt_0);
  xnor_410 <= lut4(x"9999", '0', '0', '0', wcnt_1);
  xnor_411 <= lut4(x"9999", '0', '0', '1', wcnt_2);
  xnor_412 <= lut4(x"9999", '0', '0', '0', wcnt_3);
  xnor_417 <= lut4(x"9999", '0', '0', '0', wcnt_0);
  xnor_418 <= lut4(x"9999", '0', '0', '1', wcnt_1);
  xnor_419 <= lut4(x"9999", '0', '0', '1', wcnt_2);
  xnor_420 <= lut4(x"9999", '0', '0', '0', wcnt_3);
  xnor_425 <= lut4(x"9999", '0', '0', '1', wcnt_0);
  xnor_426 <= lut4(x"9999", '0', '0', '1', wcnt_1);
  xnor_427 <= lut4(x"9999", '0', '0', '1', wcnt_2);
  xnor_428 <= lut4(x"9999", '0', '0', '0', wcnt_3);
  xor3_433 <= lut4(x"9696", '0', '0', '1', wcnt_0);
  maj_434 <= lut4(x"E8E8", '0', '0', '1', wcnt_0);
  xnor_449 <= lut4(x"9999", '0', '0', '0', akcnt_0);
  xnor_450 <= lut4(x"9999", '0', '0', '0', akcnt_1);
  xnor_454 <= lut4(x"9999", '0', '0', '1', akcnt_0);
  xnor_455 <= lut4(x"9999", '0', '0', '0', akcnt_1);
  xnor_459 <= lut4(x"9999", '0', '0', '0', akcnt_0);
  xnor_460 <= lut4(x"9999", '0', '0', '1', akcnt_1);
  xnor_464 <= lut4(x"9999", '0', '0', '1', akcnt_0);
  xnor_465 <= lut4(x"9999", '0', '0', '1', akcnt_1);
  xnor_469 <= lut4(x"9999", '0', '0', '0', akcnt_0);
  xnor_470 <= lut4(x"9999", '0', '0', '0', akcnt_1);
  xnor_474 <= lut4(x"9999", '0', '0', '1', akcnt_0);
  xnor_475 <= lut4(x"9999", '0', '0', '0', akcnt_1);
  xnor_479 <= lut4(x"9999", '0', '0', '0', akcnt_0);
  xnor_480 <= lut4(x"9999", '0', '0', '1', akcnt_1);
  xnor_484 <= lut4(x"9999", '0', '0', '1', akcnt_0);
  xnor_485 <= lut4(x"9999", '0', '0', '1', akcnt_1);
  xor3_489 <= lut4(x"9696", '0', '0', '1', akcnt_0);
  maj_490 <= lut4(x"E8E8", '0', '0', '1', akcnt_0);
  k_505 <= unsigned'(x"00000000");
  k_506 <= unsigned'(x"00000000");
  and_509 <= lut4(x"8888", '0', '0', s_ready, s_hv);
  not_545 <= lut4(x"5555", '0', '0', '0', s_tv);
  pe1_546 <= w_p0 + e0_0_res;
  pe1_548 <= w_p1 + e1_0_res;
  k_552 <= unsigned'(x"00000000");
  and_555 <= lut4(x"8888", '0', '0', e_ready, e_hv);
  not_576 <= lut4(x"5555", '0', '0', '0', e_tv);
  -- level 1
  and4_20 <= lut4(x"8000", xnor_19, xnor_18, xnor_17, xnor_16);
  and4_30 <= lut4(x"8000", '1', '1', xnor_29, xnor_28);
  and4_89 <= lut4(x"8000", '1', '1', xnor_88, xnor_87);
  and_91 <= lut4(x"8888", '0', '0', nand_90, pend);
  xor3_94 <= lut4(x"9696", '0', maj_93, '0', e0_0_state_1);
  maj_95 <= lut4(x"E8E8", '0', maj_93, '0', e0_0_state_1);
  sel_99 <= xa0_1 when rom_82 = '1' else xa0_0;
  sel_100 <= xa0_3 when rom_82 = '1' else xa0_2;
  sel_103 <= wt1 when rom_84 = '1' else wt0;
  sel_104 <= wt3 when rom_84 = '1' else wt2;
  and_112 <= lut4(x"8888", '0', '0', not_111, e0_0_a_valid);
  sel_130 <= pe1_129 when e0_0_o_mac = '1' else e0_0_acc;
  and4_162 <= lut4(x"8000", '1', '1', xnor_161, xnor_160);
  and_164 <= lut4(x"8888", '0', '0', nand_163, pend);
  xor3_167 <= lut4(x"9696", '0', maj_166, '0', e0_1_state_1);
  maj_168 <= lut4(x"E8E8", '0', maj_166, '0', e0_1_state_1);
  sel_172 <= xa1_1 when rom_155 = '1' else xa1_0;
  sel_173 <= xa1_3 when rom_155 = '1' else xa1_2;
  sel_176 <= wt5 when rom_157 = '1' else wt4;
  sel_177 <= wt7 when rom_157 = '1' else wt6;
  and_185 <= lut4(x"8888", '0', '0', not_184, e0_1_a_valid);
  sel_203 <= pe1_202 when e0_1_o_mac = '1' else e0_1_acc;
  and4_235 <= lut4(x"8000", '1', '1', xnor_234, xnor_233);
  and_237 <= lut4(x"8888", '0', '0', nand_236, pend);
  xor3_240 <= lut4(x"9696", '0', maj_239, '0', e1_0_state_1);
  maj_241 <= lut4(x"E8E8", '0', maj_239, '0', e1_0_state_1);
  sel_245 <= xa0_1 when rom_228 = '1' else xa0_0;
  sel_246 <= xa0_3 when rom_228 = '1' else xa0_2;
  sel_249 <= wt9 when rom_230 = '1' else wt8;
  sel_250 <= wt11 when rom_230 = '1' else wt10;
  and_258 <= lut4(x"8888", '0', '0', not_257, e1_0_a_valid);
  sel_276 <= pe1_275 when e1_0_o_mac = '1' else e1_0_acc;
  and4_308 <= lut4(x"8000", '1', '1', xnor_307, xnor_306);
  and_310 <= lut4(x"8888", '0', '0', nand_309, pend);
  xor3_313 <= lut4(x"9696", '0', maj_312, '0', e1_1_state_1);
  maj_314 <= lut4(x"E8E8", '0', maj_312, '0', e1_1_state_1);
  sel_318 <= xa1_1 when rom_301 = '1' else xa1_0;
  sel_319 <= xa1_3 when rom_301 = '1' else xa1_2;
  sel_322 <= wt13 when rom_303 = '1' else wt12;
  sel_323 <= wt15 when rom_303 = '1' else wt14;
  and_331 <= lut4(x"8888", '0', '0', not_330, e1_1_a_valid);
  sel_349 <= pe1_348 when e1_1_o_mac = '1' else e1_1_acc;
  and4_373 <= lut4(x"8000", xnor_372, xnor_371, xnor_370, xnor_369);
  and4_381 <= lut4(x"8000", xnor_380, xnor_379, xnor_378, xnor_377);
  and4_389 <= lut4(x"8000", xnor_388, xnor_387, xnor_386, xnor_385);
  and4_397 <= lut4(x"8000", xnor_396, xnor_395, xnor_394, xnor_393);
  and4_405 <= lut4(x"8000", xnor_404, xnor_403, xnor_402, xnor_401);
  and4_413 <= lut4(x"8000", xnor_412, xnor_411, xnor_410, xnor_409);
  and4_421 <= lut4(x"8000", xnor_420, xnor_419, xnor_418, xnor_417);
  and4_429 <= lut4(x"8000", xnor_428, xnor_427, xnor_426, xnor_425);
  xor3_435 <= lut4(x"9696", '0', maj_434, '0', wcnt_1);
  maj_436 <= lut4(x"E8E8", '0', maj_434, '0', wcnt_1);
  and4_451 <= lut4(x"8000", '1', '1', xnor_450, xnor_449);
  and4_456 <= lut4(x"8000", '1', '1', xnor_455, xnor_454);
  and4_461 <= lut4(x"8000", '1', '1', xnor_460, xnor_459);
  and4_466 <= lut4(x"8000", '1', '1', xnor_465, xnor_464);
  and4_471 <= lut4(x"8000", '1', '1', xnor_470, xnor_469);
  and4_476 <= lut4(x"8000", '1', '1', xnor_475, xnor_474);
  and4_481 <= lut4(x"8000", '1', '1', xnor_480, xnor_479);
  and4_486 <= lut4(x"8000", '1', '1', xnor_485, xnor_484);
  xor3_491 <= lut4(x"9696", '0', maj_490, '0', akcnt_1);
  maj_492 <= lut4(x"E8E8", '0', maj_490, '0', akcnt_1);
  and_511 <= lut4(x"8888", '0', '0', s_tv, and_509);
  pe1_547 <= pe1_546 + e0_1_res;
  pe1_549 <= pe1_548 + e1_1_res;
  rom_551 <= lut4(x"8080", '0', not_576, w_valid, e0_0_r_valid);
  and_557 <= lut4(x"8888", '0', '0', e_tv, and_555);
  -- level 2
  rom_21 <= lut4(x"4646", '0', and4_20, n_kind(1), n_kind(0));
  rom_22 <= lut4(x"ECEC", '0', and4_20, n_kind(1), n_kind(0));
  mux_96 <= lut4(x"E4E4", '0', xor3_92, e0_0_state_0, and_91);
  mux_97 <= lut4(x"E4E4", '0', xor3_94, e0_0_state_1, and_91);
  and_98 <= lut4(x"8888", '0', '0', and4_89, and_91);
  sel_101 <= sel_100 when rom_83 = '1' else sel_99;
  sel_105 <= sel_104 when rom_85 = '1' else sel_103;
  mux_107 <= lut4(x"E4E4", '0', rom_86, e0_0_a_mac, and_91);
  mux_108 <= lut4(x"E4E4", '0', and4_89, e0_0_a_last, and_91);
  a_valid_next_109 <= lut4(x"EAEA", '0', e0_0_s_valid, e0_0_a_valid, and_91);
  acc_ready_113 <= lut4(x"F7F7", '0', rom_551, e0_0_r_valid, e0_0_o_last);
  sel_133 <= k_132 when e0_0_o_last = '1' else sel_130;
  mux_169 <= lut4(x"E4E4", '0', xor3_165, e0_1_state_0, and_164);
  mux_170 <= lut4(x"E4E4", '0', xor3_167, e0_1_state_1, and_164);
  and_171 <= lut4(x"8888", '0', '0', and4_162, and_164);
  sel_174 <= sel_173 when rom_156 = '1' else sel_172;
  sel_178 <= sel_177 when rom_158 = '1' else sel_176;
  mux_180 <= lut4(x"E4E4", '0', rom_159, e0_1_a_mac, and_164);
  mux_181 <= lut4(x"E4E4", '0', and4_162, e0_1_a_last, and_164);
  a_valid_next_182 <= lut4(x"EAEA", '0', e0_1_s_valid, e0_1_a_valid, and_164);
  acc_ready_186 <= lut4(x"F7F7", '0', rom_551, e0_1_r_valid, e0_1_o_last);
  sel_206 <= k_205 when e0_1_o_last = '1' else sel_203;
  mux_242 <= lut4(x"E4E4", '0', xor3_238, e1_0_state_0, and_237);
  mux_243 <= lut4(x"E4E4", '0', xor3_240, e1_0_state_1, and_237);
  and_244 <= lut4(x"8888", '0', '0', and4_235, and_237);
  sel_247 <= sel_246 when rom_229 = '1' else sel_245;
  sel_251 <= sel_250 when rom_231 = '1' else sel_249;
  mux_253 <= lut4(x"E4E4", '0', rom_232, e1_0_a_mac, and_237);
  mux_254 <= lut4(x"E4E4", '0', and4_235, e1_0_a_last, and_237);
  a_valid_next_255 <= lut4(x"EAEA", '0', e1_0_s_valid, e1_0_a_valid, and_237);
  acc_ready_259 <= lut4(x"F7F7", '0', rom_551, e1_0_r_valid, e1_0_o_last);
  sel_279 <= k_278 when e1_0_o_last = '1' else sel_276;
  mux_315 <= lut4(x"E4E4", '0', xor3_311, e1_1_state_0, and_310);
  mux_316 <= lut4(x"E4E4", '0', xor3_313, e1_1_state_1, and_310);
  and_317 <= lut4(x"8888", '0', '0', and4_308, and_310);
  sel_320 <= sel_319 when rom_302 = '1' else sel_318;
  sel_324 <= sel_323 when rom_304 = '1' else sel_322;
  mux_326 <= lut4(x"E4E4", '0', rom_305, e1_1_a_mac, and_310);
  mux_327 <= lut4(x"E4E4", '0', and4_308, e1_1_a_last, and_310);
  a_valid_next_328 <= lut4(x"EAEA", '0', e1_1_s_valid, e1_1_a_valid, and_310);
  acc_ready_332 <= lut4(x"F7F7", '0', rom_551, e1_1_r_valid, e1_1_o_last);
  sel_352 <= k_351 when e1_1_o_last = '1' else sel_349;
  not_358 <= lut4(x"5555", '0', '0', '0', and4_30);
  xor3_437 <= lut4(x"9696", '0', maj_436, '0', wcnt_2);
  maj_438 <= lut4(x"E8E8", '0', maj_436, '0', wcnt_2);
  link_hin_556 <= lut4(x"22A2", e_tv, and_555, e_hv, rom_551);
  link_tin_558 <= lut4(x"0808", '0', and_555, e_hv, rom_551);
  link_hv_559 <= lut4(x"EEFE", and_555, e_hv, rom_551, e_tv);
  link_tv_560 <= lut4(x"3222", e_hv, rom_551, and_555, e_tv);
  -- level 3
  act_dec_23 <= lut4(x"1111", '0', '0', rom_22, rom_21);
  act_dec_24 <= lut4(x"2222", '0', '0', rom_22, rom_21);
  sel_102 <= sel_101 when and_91 = '1' else e0_0_a_x;
  sel_106 <= sel_105 when and_91 = '1' else e0_0_a_w;
  and_114 <= lut4(x"8888", '0', '0', acc_ready_113, e0_0_o_valid);
  sel_175 <= sel_174 when and_164 = '1' else e0_1_a_x;
  sel_179 <= sel_178 when and_164 = '1' else e0_1_a_w;
  and_187 <= lut4(x"8888", '0', '0', acc_ready_186, e0_1_o_valid);
  sel_248 <= sel_247 when and_237 = '1' else e1_0_a_x;
  sel_252 <= sel_251 when and_237 = '1' else e1_0_a_w;
  and_260 <= lut4(x"8888", '0', '0', acc_ready_259, e1_0_o_valid);
  sel_321 <= sel_320 when and_310 = '1' else e1_1_a_x;
  sel_325 <= sel_324 when and_310 = '1' else e1_1_a_w;
  and_333 <= lut4(x"8888", '0', '0', acc_ready_332, e1_1_o_valid);
  or_357 <= lut4(x"EEEE", '0', '0', and_98, not_356);
  act_dec_365 <= lut4(x"8888", '0', '0', rom_22, rom_21);
  xor3_439 <= lut4(x"9696", '0', maj_438, '0', wcnt_3);
  maj_440 <= lut4(x"E8E8", '0', maj_438, '0', wcnt_3);
  sel_563 <= pe1_547 when link_tin_558 = '1' else e_t0;
  sel_564 <= pe1_547 when link_hin_556 = '1' else e_h0;
  sel_568 <= pe1_549 when link_tin_558 = '1' else e_t1;
  sel_569 <= pe1_549 when link_hin_556 = '1' else e_h1;
  sel_573 <= k_552 when link_tin_558 = '1' else e_t2;
  sel_574 <= k_552 when link_hin_556 = '1' else e_h2;
  -- level 4
  and_115 <= lut4(x"8888", '0', '0', e0_0_s_valid, and_114);
  o_take_116 <= lut4(x"A2A2", '0', and_114, e0_0_o_valid, and_112);
  s_take_117 <= lut4(x"0808", '0', and_114, e0_0_o_valid, and_112);
  and_131 <= lut4(x"8888", '0', '0', e0_0_o_last, and_114);
  sel_134 <= sel_133 when and_114 = '1' else e0_0_acc;
  and_188 <= lut4(x"8888", '0', '0', e0_1_s_valid, and_187);
  o_take_189 <= lut4(x"A2A2", '0', and_187, e0_1_o_valid, and_185);
  s_take_190 <= lut4(x"0808", '0', and_187, e0_1_o_valid, and_185);
  and_204 <= lut4(x"8888", '0', '0', e0_1_o_last, and_187);
  sel_207 <= sel_206 when and_187 = '1' else e0_1_acc;
  and_261 <= lut4(x"8888", '0', '0', e1_0_s_valid, and_260);
  o_take_262 <= lut4(x"A2A2", '0', and_260, e1_0_o_valid, and_258);
  s_take_263 <= lut4(x"0808", '0', and_260, e1_0_o_valid, and_258);
  and_277 <= lut4(x"8888", '0', '0', e1_0_o_last, and_260);
  sel_280 <= sel_279 when and_260 = '1' else e1_0_acc;
  and_334 <= lut4(x"8888", '0', '0', e1_1_s_valid, and_333);
  o_take_335 <= lut4(x"A2A2", '0', and_333, e1_1_o_valid, and_331);
  s_take_336 <= lut4(x"0808", '0', and_333, e1_1_o_valid, and_331);
  and_350 <= lut4(x"8888", '0', '0', e1_1_o_last, and_333);
  sel_353 <= sel_352 when and_333 = '1' else e1_1_acc;
  or_359 <= lut4(x"EEEE", '0', '0', or_357, not_358);
  not_367 <= lut4(x"5555", '0', '0', '0', act_dec_24);
  sel_565 <= e_t0 when and_557 = '1' else sel_564;
  sel_570 <= e_t1 when and_557 = '1' else sel_569;
  sel_575 <= e_t2 when and_557 = '1' else sel_574;
  -- level 5
  o_valid_next_118 <= lut4(x"EEFE", and_114, e0_0_o_valid, o_take_116, and_115);
  sel_119 <= pe3_110 when o_take_116 = '1' else e0_0_o_p;
  mux_121 <= lut4(x"E4E4", '0', e0_0_a_mac, e0_0_o_mac, o_take_116);
  mux_123 <= lut4(x"E4E4", '0', e0_0_a_last, e0_0_o_last, o_take_116);
  s_valid_next_125 <= lut4(x"AEAE", '0', and_115, e0_0_s_valid, s_take_117);
  sel_126 <= pe3_110 when s_take_117 = '1' else e0_0_s_p;
  mux_127 <= lut4(x"E4E4", '0', e0_0_a_mac, e0_0_s_mac, s_take_117);
  mux_128 <= lut4(x"E4E4", '0', e0_0_a_last, e0_0_s_last, s_take_117);
  sel_135 <= sel_130 when and_131 = '1' else e0_0_res;
  r_valid_next_136 <= lut4(x"AEAE", '0', rom_551, e0_0_r_valid, and_131);
  o_valid_next_191 <= lut4(x"EEFE", and_187, e0_1_o_valid, o_take_189, and_188);
  sel_192 <= pe3_183 when o_take_189 = '1' else e0_1_o_p;
  mux_194 <= lut4(x"E4E4", '0', e0_1_a_mac, e0_1_o_mac, o_take_189);
  mux_196 <= lut4(x"E4E4", '0', e0_1_a_last, e0_1_o_last, o_take_189);
  s_valid_next_198 <= lut4(x"AEAE", '0', and_188, e0_1_s_valid, s_take_190);
  sel_199 <= pe3_183 when s_take_190 = '1' else e0_1_s_p;
  mux_200 <= lut4(x"E4E4", '0', e0_1_a_mac, e0_1_s_mac, s_take_190);
  mux_201 <= lut4(x"E4E4", '0', e0_1_a_last, e0_1_s_last, s_take_190);
  sel_208 <= sel_203 when and_204 = '1' else e0_1_res;
  r_valid_next_209 <= lut4(x"AEAE", '0', rom_551, e0_1_r_valid, and_204);
  o_valid_next_264 <= lut4(x"EEFE", and_260, e1_0_o_valid, o_take_262, and_261);
  sel_265 <= pe3_256 when o_take_262 = '1' else e1_0_o_p;
  mux_267 <= lut4(x"E4E4", '0', e1_0_a_mac, e1_0_o_mac, o_take_262);
  mux_269 <= lut4(x"E4E4", '0', e1_0_a_last, e1_0_o_last, o_take_262);
  s_valid_next_271 <= lut4(x"AEAE", '0', and_261, e1_0_s_valid, s_take_263);
  sel_272 <= pe3_256 when s_take_263 = '1' else e1_0_s_p;
  mux_273 <= lut4(x"E4E4", '0', e1_0_a_mac, e1_0_s_mac, s_take_263);
  mux_274 <= lut4(x"E4E4", '0', e1_0_a_last, e1_0_s_last, s_take_263);
  sel_281 <= sel_276 when and_277 = '1' else e1_0_res;
  r_valid_next_282 <= lut4(x"AEAE", '0', rom_551, e1_0_r_valid, and_277);
  o_valid_next_337 <= lut4(x"EEFE", and_333, e1_1_o_valid, o_take_335, and_334);
  sel_338 <= pe3_329 when o_take_335 = '1' else e1_1_o_p;
  mux_340 <= lut4(x"E4E4", '0', e1_1_a_mac, e1_1_o_mac, o_take_335);
  mux_342 <= lut4(x"E4E4", '0', e1_1_a_last, e1_1_o_last, o_take_335);
  s_valid_next_344 <= lut4(x"AEAE", '0', and_334, e1_1_s_valid, s_take_336);
  sel_345 <= pe3_329 when s_take_336 = '1' else e1_1_s_p;
  mux_346 <= lut4(x"E4E4", '0', e1_1_a_mac, e1_1_s_mac, s_take_336);
  mux_347 <= lut4(x"E4E4", '0', e1_1_a_last, e1_1_s_last, s_take_336);
  sel_354 <= sel_349 when and_350 = '1' else e1_1_res;
  r_valid_next_355 <= lut4(x"AEAE", '0', rom_551, e1_1_r_valid, and_350);
  rom_361 <= lut4(x"F2E2", or_359, not_545, rom_22, rom_21);
  -- level 6
  sel_120 <= e0_0_s_p when and_115 = '1' else sel_119;
  mux_122 <= lut4(x"E4E4", '0', e0_0_s_mac, mux_121, and_115);
  mux_124 <= lut4(x"E4E4", '0', e0_0_s_last, mux_123, and_115);
  sel_193 <= e0_1_s_p when and_188 = '1' else sel_192;
  mux_195 <= lut4(x"E4E4", '0', e0_1_s_mac, mux_194, and_188);
  mux_197 <= lut4(x"E4E4", '0', e0_1_s_last, mux_196, and_188);
  sel_266 <= e1_0_s_p when and_261 = '1' else sel_265;
  mux_268 <= lut4(x"E4E4", '0', e1_0_s_mac, mux_267, and_261);
  mux_270 <= lut4(x"E4E4", '0', e1_0_s_last, mux_269, and_261);
  sel_339 <= e1_1_s_p when and_334 = '1' else sel_338;
  mux_341 <= lut4(x"E4E4", '0', e1_1_s_mac, mux_340, and_334);
  mux_343 <= lut4(x"E4E4", '0', e1_1_s_last, mux_342, and_334);
  and_362 <= lut4(x"8888", '0', '0', rom_361, n_valid);
  -- level 7
  and_363 <= lut4(x"8888", '0', '0', act_dec_23, and_362);
  and_364 <= lut4(x"8888", '0', '0', act_dec_24, and_362);
  and_366 <= lut4(x"8888", '0', '0', act_dec_365, and_362);
  and_368 <= lut4(x"8888", '0', '0', not_367, and_362);
  -- level 8
  and_374 <= lut4(x"8888", '0', '0', and4_373, and_364);
  and_382 <= lut4(x"8888", '0', '0', and4_381, and_364);
  and_390 <= lut4(x"8888", '0', '0', and4_389, and_364);
  and_398 <= lut4(x"8888", '0', '0', and4_397, and_364);
  and_406 <= lut4(x"8888", '0', '0', and4_405, and_364);
  and_414 <= lut4(x"8888", '0', '0', and4_413, and_364);
  and_422 <= lut4(x"8888", '0', '0', and4_421, and_364);
  and_430 <= lut4(x"8888", '0', '0', and4_429, and_364);
  mux_441 <= lut4(x"E4E4", '0', xor3_433, wcnt_0, and_364);
  mux_442 <= lut4(x"E4E4", '0', xor3_435, wcnt_1, and_364);
  mux_443 <= lut4(x"E4E4", '0', xor3_437, wcnt_2, and_364);
  mux_444 <= lut4(x"E4E4", '0', xor3_439, wcnt_3, and_364);
  and_452 <= lut4(x"8888", '0', '0', and4_451, and_363);
  and_457 <= lut4(x"8888", '0', '0', and4_456, and_363);
  and_462 <= lut4(x"8888", '0', '0', and4_461, and_363);
  and_467 <= lut4(x"8888", '0', '0', and4_466, and_363);
  and_472 <= lut4(x"8888", '0', '0', and4_471, and_363);
  and_477 <= lut4(x"8888", '0', '0', and4_476, and_363);
  and_482 <= lut4(x"8888", '0', '0', and4_481, and_363);
  and_487 <= lut4(x"8888", '0', '0', and4_486, and_363);
  mux_493 <= lut4(x"E4E4", '0', xor3_489, akcnt_0, and_363);
  mux_494 <= lut4(x"E4E4", '0', xor3_491, akcnt_1, and_363);
  and_495 <= lut4(x"8888", '0', '0', and4_30, and_363);
  link_hin_510 <= lut4(x"22A2", s_tv, and_509, s_hv, and_368);
  link_tin_512 <= lut4(x"0808", '0', and_509, s_hv, and_368);
  link_hv_513 <= lut4(x"EEFE", and_509, s_hv, and_368, s_tv);
  link_tv_514 <= lut4(x"3222", s_hv, and_368, and_509, s_tv);
  -- level 9
  sel_375 <= n_d0 when and_374 = '1' else wt0;
  sel_376 <= n_d1 when and_374 = '1' else wt4;
  sel_383 <= n_d0 when and_382 = '1' else wt1;
  sel_384 <= n_d1 when and_382 = '1' else wt5;
  sel_391 <= n_d0 when and_390 = '1' else wt2;
  sel_392 <= n_d1 when and_390 = '1' else wt6;
  sel_399 <= n_d0 when and_398 = '1' else wt3;
  sel_400 <= n_d1 when and_398 = '1' else wt7;
  sel_407 <= n_d0 when and_406 = '1' else wt8;
  sel_408 <= n_d1 when and_406 = '1' else wt12;
  sel_415 <= n_d0 when and_414 = '1' else wt9;
  sel_416 <= n_d1 when and_414 = '1' else wt13;
  sel_423 <= n_d0 when and_422 = '1' else wt10;
  sel_424 <= n_d1 when and_422 = '1' else wt14;
  sel_431 <= n_d0 when and_430 = '1' else wt11;
  sel_432 <= n_d1 when and_430 = '1' else wt15;
  mux_445 <= lut4(x"E4E4", '0', '0', mux_441, and_366);
  mux_446 <= lut4(x"E4E4", '0', '0', mux_442, and_366);
  mux_447 <= lut4(x"E4E4", '0', '0', mux_443, and_366);
  mux_448 <= lut4(x"E4E4", '0', '0', mux_444, and_366);
  sel_453 <= n_d0 when and_452 = '1' else xs0_0;
  sel_458 <= n_d0 when and_457 = '1' else xs0_1;
  sel_463 <= n_d0 when and_462 = '1' else xs0_2;
  sel_468 <= n_d0 when and_467 = '1' else xs0_3;
  sel_473 <= n_d1 when and_472 = '1' else xs1_0;
  sel_478 <= n_d1 when and_477 = '1' else xs1_1;
  sel_483 <= n_d1 when and_482 = '1' else xs1_2;
  sel_488 <= n_d1 when and_487 = '1' else xs1_3;
  pend_next_504 <= lut4(x"AEAE", '0', and_98, pend, and_495);
  sel_517 <= n_d0 when link_tin_512 = '1' else s_t0;
  sel_518 <= n_d0 when link_hin_510 = '1' else s_h0;
  sel_522 <= n_d1 when link_tin_512 = '1' else s_t1;
  sel_523 <= n_d1 when link_hin_510 = '1' else s_h1;
  sel_527 <= k_505 when link_tin_512 = '1' else s_t2;
  sel_528 <= k_505 when link_hin_510 = '1' else s_h2;
  sel_532 <= k_506 when link_tin_512 = '1' else s_t3;
  sel_533 <= k_506 when link_hin_510 = '1' else s_h3;
  mux_537 <= lut4(x"E4E4", '0', n_kind(0), s_tb0, link_tin_512);
  mux_538 <= lut4(x"E4E4", '0', n_kind(0), s_hb0, link_hin_510);
  mux_542 <= lut4(x"E4E4", '0', n_kind(1), s_tb1, link_tin_512);
  mux_543 <= lut4(x"E4E4", '0', n_kind(1), s_hb1, link_hin_510);
  -- level 10
  sel_496 <= sel_453 when and_495 = '1' else xa0_0;
  sel_497 <= sel_458 when and_495 = '1' else xa0_1;
  sel_498 <= sel_463 when and_495 = '1' else xa0_2;
  sel_499 <= sel_468 when and_495 = '1' else xa0_3;
  sel_500 <= sel_473 when and_495 = '1' else xa1_0;
  sel_501 <= sel_478 when and_495 = '1' else xa1_1;
  sel_502 <= sel_483 when and_495 = '1' else xa1_2;
  sel_503 <= sel_488 when and_495 = '1' else xa1_3;
  sel_519 <= s_t0 when and_511 = '1' else sel_518;
  sel_524 <= s_t1 when and_511 = '1' else sel_523;
  sel_529 <= s_t2 when and_511 = '1' else sel_528;
  sel_534 <= s_t3 when and_511 = '1' else sel_533;
  mux_539 <= lut4(x"E4E4", '0', s_tb0, mux_538, and_511);
  mux_544 <= lut4(x"E4E4", '0', s_tb1, mux_543, and_511);
  -- the clock edge
  process (clk)
  begin
    if rising_edge(clk) then
      if rst = '1' then
        wcnt_0 <= '0';
        wcnt_1 <= '0';
        wcnt_2 <= '0';
        wcnt_3 <= '0';
        akcnt_0 <= '0';
        akcnt_1 <= '0';
        pend <= '0';
        xs0_0 <= x"00000000";
        xa0_0 <= x"00000000";
        xs0_1 <= x"00000000";
        xa0_1 <= x"00000000";
        xs0_2 <= x"00000000";
        xa0_2 <= x"00000000";
        xs0_3 <= x"00000000";
        xa0_3 <= x"00000000";
        xs1_0 <= x"00000000";
        xa1_0 <= x"00000000";
        xs1_1 <= x"00000000";
        xa1_1 <= x"00000000";
        xs1_2 <= x"00000000";
        xa1_2 <= x"00000000";
        xs1_3 <= x"00000000";
        xa1_3 <= x"00000000";
        wt0 <= x"00000000";
        wt1 <= x"00000000";
        wt2 <= x"00000000";
        wt3 <= x"00000000";
        wt4 <= x"00000000";
        wt5 <= x"00000000";
        wt6 <= x"00000000";
        wt7 <= x"00000000";
        wt8 <= x"00000000";
        wt9 <= x"00000000";
        wt10 <= x"00000000";
        wt11 <= x"00000000";
        wt12 <= x"00000000";
        wt13 <= x"00000000";
        wt14 <= x"00000000";
        wt15 <= x"00000000";
        e0_0_state_0 <= '0';
        e0_0_state_1 <= '0';
        e0_0_o_valid <= '0';
        e0_0_o_mac <= '0';
        e0_0_o_last <= '0';
        e0_0_s_valid <= '0';
        e0_0_s_mac <= '0';
        e0_0_s_last <= '0';
        e0_0_r_valid <= '0';
        e0_0_o_p <= x"00000000";
        e0_0_s_p <= x"00000000";
        e0_0_acc <= x"00000000";
        e0_0_res <= x"00000000";
        e0_0_a_valid <= '0';
        e0_0_a_mac <= '0';
        e0_0_a_last <= '0';
        e0_0_a_x <= x"00000000";
        e0_0_a_w <= x"00000000";
        e0_1_state_0 <= '0';
        e0_1_state_1 <= '0';
        e0_1_o_valid <= '0';
        e0_1_o_mac <= '0';
        e0_1_o_last <= '0';
        e0_1_s_valid <= '0';
        e0_1_s_mac <= '0';
        e0_1_s_last <= '0';
        e0_1_r_valid <= '0';
        e0_1_o_p <= x"00000000";
        e0_1_s_p <= x"00000000";
        e0_1_acc <= x"00000000";
        e0_1_res <= x"00000000";
        e0_1_a_valid <= '0';
        e0_1_a_mac <= '0';
        e0_1_a_last <= '0';
        e0_1_a_x <= x"00000000";
        e0_1_a_w <= x"00000000";
        e1_0_state_0 <= '0';
        e1_0_state_1 <= '0';
        e1_0_o_valid <= '0';
        e1_0_o_mac <= '0';
        e1_0_o_last <= '0';
        e1_0_s_valid <= '0';
        e1_0_s_mac <= '0';
        e1_0_s_last <= '0';
        e1_0_r_valid <= '0';
        e1_0_o_p <= x"00000000";
        e1_0_s_p <= x"00000000";
        e1_0_acc <= x"00000000";
        e1_0_res <= x"00000000";
        e1_0_a_valid <= '0';
        e1_0_a_mac <= '0';
        e1_0_a_last <= '0';
        e1_0_a_x <= x"00000000";
        e1_0_a_w <= x"00000000";
        e1_1_state_0 <= '0';
        e1_1_state_1 <= '0';
        e1_1_o_valid <= '0';
        e1_1_o_mac <= '0';
        e1_1_o_last <= '0';
        e1_1_s_valid <= '0';
        e1_1_s_mac <= '0';
        e1_1_s_last <= '0';
        e1_1_r_valid <= '0';
        e1_1_o_p <= x"00000000";
        e1_1_s_p <= x"00000000";
        e1_1_acc <= x"00000000";
        e1_1_res <= x"00000000";
        e1_1_a_valid <= '0';
        e1_1_a_mac <= '0';
        e1_1_a_last <= '0';
        e1_1_a_x <= x"00000000";
        e1_1_a_w <= x"00000000";
        s_hv <= '0';
        s_tv <= '0';
        s_h0 <= x"00000000";
        s_t0 <= x"00000000";
        s_h1 <= x"00000000";
        s_t1 <= x"00000000";
        s_h2 <= x"00000000";
        s_t2 <= x"00000000";
        s_h3 <= x"00000000";
        s_t3 <= x"00000000";
        s_hb0 <= '0';
        s_tb0 <= '0';
        s_hb1 <= '0';
        s_tb1 <= '0';
        e_hv <= '0';
        e_tv <= '0';
        e_h0 <= x"00000000";
        e_t0 <= x"00000000";
        e_h1 <= x"00000000";
        e_t1 <= x"00000000";
        e_h2 <= x"00000000";
        e_t2 <= x"00000000";
      else
        wcnt_0 <= mux_445;
        wcnt_1 <= mux_446;
        wcnt_2 <= mux_447;
        wcnt_3 <= mux_448;
        akcnt_0 <= mux_493;
        akcnt_1 <= mux_494;
        pend <= pend_next_504;
        xs0_0 <= sel_453;
        xa0_0 <= sel_496;
        xs0_1 <= sel_458;
        xa0_1 <= sel_497;
        xs0_2 <= sel_463;
        xa0_2 <= sel_498;
        xs0_3 <= sel_468;
        xa0_3 <= sel_499;
        xs1_0 <= sel_473;
        xa1_0 <= sel_500;
        xs1_1 <= sel_478;
        xa1_1 <= sel_501;
        xs1_2 <= sel_483;
        xa1_2 <= sel_502;
        xs1_3 <= sel_488;
        xa1_3 <= sel_503;
        wt0 <= sel_375;
        wt1 <= sel_383;
        wt2 <= sel_391;
        wt3 <= sel_399;
        wt4 <= sel_376;
        wt5 <= sel_384;
        wt6 <= sel_392;
        wt7 <= sel_400;
        wt8 <= sel_407;
        wt9 <= sel_415;
        wt10 <= sel_423;
        wt11 <= sel_431;
        wt12 <= sel_408;
        wt13 <= sel_416;
        wt14 <= sel_424;
        wt15 <= sel_432;
        e0_0_state_0 <= mux_96;
        e0_0_state_1 <= mux_97;
        e0_0_o_valid <= o_valid_next_118;
        e0_0_o_mac <= mux_122;
        e0_0_o_last <= mux_124;
        e0_0_s_valid <= s_valid_next_125;
        e0_0_s_mac <= mux_127;
        e0_0_s_last <= mux_128;
        e0_0_r_valid <= r_valid_next_136;
        e0_0_o_p <= sel_120;
        e0_0_s_p <= sel_126;
        e0_0_acc <= sel_134;
        e0_0_res <= sel_135;
        e0_0_a_valid <= a_valid_next_109;
        e0_0_a_mac <= mux_107;
        e0_0_a_last <= mux_108;
        e0_0_a_x <= sel_102;
        e0_0_a_w <= sel_106;
        e0_1_state_0 <= mux_169;
        e0_1_state_1 <= mux_170;
        e0_1_o_valid <= o_valid_next_191;
        e0_1_o_mac <= mux_195;
        e0_1_o_last <= mux_197;
        e0_1_s_valid <= s_valid_next_198;
        e0_1_s_mac <= mux_200;
        e0_1_s_last <= mux_201;
        e0_1_r_valid <= r_valid_next_209;
        e0_1_o_p <= sel_193;
        e0_1_s_p <= sel_199;
        e0_1_acc <= sel_207;
        e0_1_res <= sel_208;
        e0_1_a_valid <= a_valid_next_182;
        e0_1_a_mac <= mux_180;
        e0_1_a_last <= mux_181;
        e0_1_a_x <= sel_175;
        e0_1_a_w <= sel_179;
        e1_0_state_0 <= mux_242;
        e1_0_state_1 <= mux_243;
        e1_0_o_valid <= o_valid_next_264;
        e1_0_o_mac <= mux_268;
        e1_0_o_last <= mux_270;
        e1_0_s_valid <= s_valid_next_271;
        e1_0_s_mac <= mux_273;
        e1_0_s_last <= mux_274;
        e1_0_r_valid <= r_valid_next_282;
        e1_0_o_p <= sel_266;
        e1_0_s_p <= sel_272;
        e1_0_acc <= sel_280;
        e1_0_res <= sel_281;
        e1_0_a_valid <= a_valid_next_255;
        e1_0_a_mac <= mux_253;
        e1_0_a_last <= mux_254;
        e1_0_a_x <= sel_248;
        e1_0_a_w <= sel_252;
        e1_1_state_0 <= mux_315;
        e1_1_state_1 <= mux_316;
        e1_1_o_valid <= o_valid_next_337;
        e1_1_o_mac <= mux_341;
        e1_1_o_last <= mux_343;
        e1_1_s_valid <= s_valid_next_344;
        e1_1_s_mac <= mux_346;
        e1_1_s_last <= mux_347;
        e1_1_r_valid <= r_valid_next_355;
        e1_1_o_p <= sel_339;
        e1_1_s_p <= sel_345;
        e1_1_acc <= sel_353;
        e1_1_res <= sel_354;
        e1_1_a_valid <= a_valid_next_328;
        e1_1_a_mac <= mux_326;
        e1_1_a_last <= mux_327;
        e1_1_a_x <= sel_321;
        e1_1_a_w <= sel_325;
        s_hv <= link_hv_513;
        s_tv <= link_tv_514;
        s_h0 <= sel_519;
        s_t0 <= sel_517;
        s_h1 <= sel_524;
        s_t1 <= sel_522;
        s_h2 <= sel_529;
        s_t2 <= sel_527;
        s_h3 <= sel_534;
        s_t3 <= sel_532;
        s_hb0 <= mux_539;
        s_tb0 <= mux_537;
        s_hb1 <= mux_544;
        s_tb1 <= mux_542;
        e_hv <= link_hv_559;
        e_tv <= link_tv_560;
        e_h0 <= sel_565;
        e_t0 <= sel_563;
        e_h1 <= sel_570;
        e_t1 <= sel_568;
        e_h2 <= sel_575;
        e_t2 <= sel_573;
      end if;
    end if;
  end process;
  -- outputs
  n_ready <= rom_361;
  s_valid <= s_hv;
  s_kind <= s_hb1 & s_hb0;
  s_d0 <= s_h0;
  s_d1 <= s_h1;
  w_ready <= rom_551;
  e_valid <= e_hv;
  e_p0 <= e_h0;
  e_p1 <= e_h1;
end architecture fabric;
