-- jev_mesh_2x2_tb.vhd -- self-checking testbench generated by the WASMApollo EDA; the expected
-- values are the fabric's golden model (RefSim). Run: ghdl -a jev_mesh_2x2.vhd jev_mesh_2x2_tb.vhd && ghdl -e jev_mesh_2x2_tb && ghdl -r jev_mesh_2x2_tb

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity jev_mesh_2x2_tb is
end entity jev_mesh_2x2_tb;

architecture sim of jev_mesh_2x2_tb is
  signal clk : std_logic := '0';
  signal rst : std_logic := '1';
  signal finished : boolean := false;
  signal n_valid : std_logic := '0';
  signal n_kind : std_logic_vector(1 downto 0) := (others => '0');
  signal n_d0 : unsigned(31 downto 0) := (others => '0');
  signal n_d1 : unsigned(31 downto 0) := (others => '0');
  signal s_ready : std_logic := '0';
  signal w_valid : std_logic := '0';
  signal w_p0 : unsigned(31 downto 0) := (others => '0');
  signal w_p1 : unsigned(31 downto 0) := (others => '0');
  signal e_ready : std_logic := '0';
  signal n_ready : std_logic;
  signal s_valid : std_logic;
  signal s_kind : std_logic_vector(1 downto 0);
  signal s_d0 : unsigned(31 downto 0);
  signal s_d1 : unsigned(31 downto 0);
  signal w_ready : std_logic;
  signal e_valid : std_logic;
  signal e_p0 : unsigned(31 downto 0);
  signal e_p1 : unsigned(31 downto 0);
begin
  dut : entity work.jev_mesh_2x2 port map (clk => clk, rst => rst, n_valid => n_valid, n_kind => n_kind, n_d0 => n_d0, n_d1 => n_d1, s_ready => s_ready, w_valid => w_valid, w_p0 => w_p0, w_p1 => w_p1, e_ready => e_ready, n_ready => n_ready, s_valid => s_valid, s_kind => s_kind, s_d0 => s_d0, s_d1 => s_d1, w_ready => w_ready, e_valid => e_valid, e_p0 => e_p0, e_p1 => e_p1);
  clk <= not clk after 5 ns when not finished else '0';

  check : process
    variable errors : natural := 0;
    procedure tick is
    begin
      wait until rising_edge(clk);
      wait for 1 ns;
    end procedure;
  begin
    -- vector 0
    n_valid <= '1';
    n_kind <= "00";
    n_d0 <= x"00007B06";
    n_d1 <= x"000040FB";
    s_ready <= '1';
    w_valid <= '1';
    w_p0 <= x"000090B6";
    w_p1 <= x"0000CF5A";
    e_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '1' then
      report "FAIL vector 0: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '1' then
      report "FAIL vector 0: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "00" then
      report "FAIL vector 0: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"00007B06" then
      report "FAIL vector 0: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"000040FB" then
      report "FAIL vector 0: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 0: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 0: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"000090B6" then
      report "FAIL vector 0: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"0000CF5A" then
      report "FAIL vector 0: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 1
    n_valid <= '1';
    n_kind <= "00";
    n_d0 <= x"000099B2";
    n_d1 <= x"0000B1AB";
    s_ready <= '1';
    w_valid <= '1';
    w_p0 <= x"00002B5E";
    w_p1 <= x"000098E9";
    e_ready <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '0' then
      report "FAIL vector 1: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '0' then
      report "FAIL vector 1: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "00" then
      report "FAIL vector 1: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"000099B2" then
      report "FAIL vector 1: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"0000B1AB" then
      report "FAIL vector 1: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 1: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '1' then
      report "FAIL vector 1: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00002B5E" then
      report "FAIL vector 1: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"000098E9" then
      report "FAIL vector 1: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 2
    n_valid <= '1';
    n_kind <= "00";
    n_d0 <= x"0000B6EC";
    n_d1 <= x"0000952A";
    s_ready <= '0';
    w_valid <= '1';
    w_p0 <= x"0000E783";
    w_p1 <= x"0000EACD";
    e_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '0' then
      report "FAIL vector 2: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '1' then
      report "FAIL vector 2: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "00" then
      report "FAIL vector 2: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"0000B6EC" then
      report "FAIL vector 2: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"0000952A" then
      report "FAIL vector 2: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 2: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 2: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 2: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 2: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 3
    n_valid <= '0';
    n_kind <= "00";
    n_d0 <= x"0000C21A";
    n_d1 <= x"00003F53";
    s_ready <= '1';
    w_valid <= '1';
    w_p0 <= x"000076B5";
    w_p1 <= x"00003D19";
    e_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '1' then
      report "FAIL vector 3: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '0' then
      report "FAIL vector 3: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "00" then
      report "FAIL vector 3: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"00000000" then
      report "FAIL vector 3: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"00000000" then
      report "FAIL vector 3: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 3: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 3: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 3: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 3: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 4
    n_valid <= '1';
    n_kind <= "01";
    n_d0 <= x"00004C06";
    n_d1 <= x"0000CA5F";
    s_ready <= '1';
    w_valid <= '0';
    w_p0 <= x"00002CDB";
    w_p1 <= x"000026CF";
    e_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '1' then
      report "FAIL vector 4: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '1' then
      report "FAIL vector 4: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "01" then
      report "FAIL vector 4: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"00004C06" then
      report "FAIL vector 4: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"0000CA5F" then
      report "FAIL vector 4: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 4: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 4: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 4: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 4: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 5
    n_valid <= '1';
    n_kind <= "01";
    n_d0 <= x"00009E9A";
    n_d1 <= x"000064AC";
    s_ready <= '0';
    w_valid <= '1';
    w_p0 <= x"00000207";
    w_p1 <= x"00000065";
    e_ready <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '0' then
      report "FAIL vector 5: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '1' then
      report "FAIL vector 5: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "01" then
      report "FAIL vector 5: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"00009E9A" then
      report "FAIL vector 5: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"000064AC" then
      report "FAIL vector 5: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 5: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 5: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 5: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 5: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 6
    n_valid <= '1';
    n_kind <= "01";
    n_d0 <= x"00009D21";
    n_d1 <= x"0000681E";
    s_ready <= '1';
    w_valid <= '1';
    w_p0 <= x"0000AC23";
    w_p1 <= x"0000D117";
    e_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '1' then
      report "FAIL vector 6: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '1' then
      report "FAIL vector 6: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "01" then
      report "FAIL vector 6: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"00009D21" then
      report "FAIL vector 6: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"0000681E" then
      report "FAIL vector 6: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 6: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 6: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 6: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 6: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 7
    n_valid <= '0';
    n_kind <= "01";
    n_d0 <= x"0000A93E";
    n_d1 <= x"0000C78D";
    s_ready <= '1';
    w_valid <= '1';
    w_p0 <= x"0000048B";
    w_p1 <= x"000087E0";
    e_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '1' then
      report "FAIL vector 7: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '0' then
      report "FAIL vector 7: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "00" then
      report "FAIL vector 7: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"00000000" then
      report "FAIL vector 7: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"00000000" then
      report "FAIL vector 7: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 7: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 7: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 7: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 7: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 8
    n_valid <= '1';
    n_kind <= "10";
    n_d0 <= x"00009829";
    n_d1 <= x"000099A1";
    s_ready <= '0';
    w_valid <= '1';
    w_p0 <= x"0000965E";
    w_p1 <= x"00002496";
    e_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '0' then
      report "FAIL vector 8: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '1' then
      report "FAIL vector 8: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "10" then
      report "FAIL vector 8: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"00009829" then
      report "FAIL vector 8: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"000099A1" then
      report "FAIL vector 8: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 8: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 8: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 8: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 8: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 9
    n_valid <= '1';
    n_kind <= "10";
    n_d0 <= x"0000EE70";
    n_d1 <= x"0000E23E";
    s_ready <= '1';
    w_valid <= '0';
    w_p0 <= x"00005F2F";
    w_p1 <= x"00002A90";
    e_ready <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '1' then
      report "FAIL vector 9: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '1' then
      report "FAIL vector 9: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "10" then
      report "FAIL vector 9: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"0000EE70" then
      report "FAIL vector 9: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"0000E23E" then
      report "FAIL vector 9: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 9: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 9: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 9: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 9: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 10
    n_valid <= '1';
    n_kind <= "10";
    n_d0 <= x"00009BCF";
    n_d1 <= x"0000BA3F";
    s_ready <= '1';
    w_valid <= '1';
    w_p0 <= x"00009220";
    w_p1 <= x"000052D9";
    e_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '1' then
      report "FAIL vector 10: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '1' then
      report "FAIL vector 10: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "10" then
      report "FAIL vector 10: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"00009BCF" then
      report "FAIL vector 10: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"0000BA3F" then
      report "FAIL vector 10: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 10: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 10: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 10: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 10: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 11
    n_valid <= '0';
    n_kind <= "10";
    n_d0 <= x"00003789";
    n_d1 <= x"0000AAF1";
    s_ready <= '0';
    w_valid <= '1';
    w_p0 <= x"0000F617";
    w_p1 <= x"0000E2FB";
    e_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '1' then
      report "FAIL vector 11: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '0' then
      report "FAIL vector 11: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "00" then
      report "FAIL vector 11: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"00000000" then
      report "FAIL vector 11: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"00000000" then
      report "FAIL vector 11: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 11: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 11: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 11: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 11: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 12
    n_valid <= '1';
    n_kind <= "11";
    n_d0 <= x"00009F0C";
    n_d1 <= x"000045C6";
    s_ready <= '1';
    w_valid <= '1';
    w_p0 <= x"00003DF3";
    w_p1 <= x"000084B6";
    e_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '1' then
      report "FAIL vector 12: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '1' then
      report "FAIL vector 12: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "11" then
      report "FAIL vector 12: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"00009F0C" then
      report "FAIL vector 12: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"000045C6" then
      report "FAIL vector 12: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 12: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 12: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 12: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 12: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 13
    n_valid <= '1';
    n_kind <= "11";
    n_d0 <= x"00000883";
    n_d1 <= x"00003E27";
    s_ready <= '1';
    w_valid <= '1';
    w_p0 <= x"0000D68F";
    w_p1 <= x"0000EA1A";
    e_ready <= '0';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '1' then
      report "FAIL vector 13: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '1' then
      report "FAIL vector 13: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "11" then
      report "FAIL vector 13: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"00000883" then
      report "FAIL vector 13: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"00003E27" then
      report "FAIL vector 13: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 13: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 13: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 13: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 13: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 14
    n_valid <= '1';
    n_kind <= "11";
    n_d0 <= x"0000712A";
    n_d1 <= x"0000DE7F";
    s_ready <= '0';
    w_valid <= '0';
    w_p0 <= x"0000A4BD";
    w_p1 <= x"0000C75C";
    e_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '0' then
      report "FAIL vector 14: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '1' then
      report "FAIL vector 14: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "11" then
      report "FAIL vector 14: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"0000712A" then
      report "FAIL vector 14: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"0000DE7F" then
      report "FAIL vector 14: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 14: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 14: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 14: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 14: e_p1" severity error;
      errors := errors + 1;
    end if;
    -- vector 15
    n_valid <= '0';
    n_kind <= "11";
    n_d0 <= x"00003668";
    n_d1 <= x"0000FA98";
    s_ready <= '1';
    w_valid <= '1';
    w_p0 <= x"0000CD1F";
    w_p1 <= x"000083F4";
    e_ready <= '1';
    rst <= '1';
    tick;
    rst <= '0';
    for i in 1 to 24 loop
      tick;
    end loop;
    if n_ready /= '1' then
      report "FAIL vector 15: n_ready" severity error;
      errors := errors + 1;
    end if;
    if s_valid /= '0' then
      report "FAIL vector 15: s_valid" severity error;
      errors := errors + 1;
    end if;
    if s_kind /= "00" then
      report "FAIL vector 15: s_kind" severity error;
      errors := errors + 1;
    end if;
    if s_d0 /= x"00000000" then
      report "FAIL vector 15: s_d0" severity error;
      errors := errors + 1;
    end if;
    if s_d1 /= x"00000000" then
      report "FAIL vector 15: s_d1" severity error;
      errors := errors + 1;
    end if;
    if w_ready /= '0' then
      report "FAIL vector 15: w_ready" severity error;
      errors := errors + 1;
    end if;
    if e_valid /= '0' then
      report "FAIL vector 15: e_valid" severity error;
      errors := errors + 1;
    end if;
    if e_p0 /= x"00000000" then
      report "FAIL vector 15: e_p0" severity error;
      errors := errors + 1;
    end if;
    if e_p1 /= x"00000000" then
      report "FAIL vector 15: e_p1" severity error;
      errors := errors + 1;
    end if;
    if errors = 0 then
      report "PASS jev_mesh_2x2: 16 vectors";
    else
      report "FAIL jev_mesh_2x2: " & integer'image(errors) & " mismatches" severity failure;
    end if;
    finished <= true;
    wait;
  end process;
end architecture sim;
